table M_Measures
	lineageTag: 0686b20f-f7b0-4b8f-b330-dd1b0c0c4dbc

	measure 'Actual Amount' =
			
			SUM(GL_Actual[Amount])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 68878804-36d7-4f21-b79c-b016615d5d62

	measure 'Budget Amount' =
			
			SUM(GL_Budget[BudgetAmount])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: d80f1dd4-c238-41ef-9c94-afe1962d625f

	measure Variance0 =
			
			[Actual Amount] - [Budget Amount]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: bfaa34f0-4928-479e-950e-de5ece91b0c7

	measure 'Variance0 %' =
			
			DIVIDE([Variance0], [Budget Amount],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 93c32a84-103f-48c6-b010-189d85593caa

	/// Actual value - Deductions sign = 1 (source already negative). Rewritten as a single vectorized SUMX over the fact table (sign precomputed on Dim_Accounts) instead of SUMX-over-dimension with per-account context transition - eliminates the per-account storage-engine round trips that made the Income Statement/Forecast matrices exceed Power BI Service's per-visual memory limit.
	measure Actual = SUMX(GL_Actual, GL_Actual[Amount] * RELATED(Dim_Accounts[ActualSign]))
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 02786b97-1034-4870-82c9-f05baf8ea1da

	/// Budget value - Deductions sign = -1 (source is positive magnitude). Rewritten as a single vectorized SUMX over the fact table (sign precomputed on Dim_Accounts) - see Actual for rationale.
	measure Budget = SUMX(GL_Budget, GL_Budget[BudgetAmount] * RELATED(Dim_Accounts[BudgetSign]))
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 3536a6ac-9467-49f0-a1c6-36b424202ccd

	measure VAR =
			
			[Actual] - [Budget]
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 980a6732-da0e-47b2-a04b-ba872ea8d14b

	measure 'VAR %' =
			
			DIVIDE([VAR],[Budget],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d47441c3-a4da-4d0e-bf25-0b56013e4abf

	measure Revenue =
			
			CALCULATE(
			    [Actual],
			    Dim_Accounts[FSGroup] = "Revenue"
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: c5edb24c-f587-4b21-9a53-d3dbe6baf929

	/// MATH FIX: was skipping Revenue Deductions entirely (Gross Profit = Revenue - COGS). Now correctly computes Net Revenue = Revenue - Deductions first, matching the Income Statement matrix logic: Gross Profit = Net Revenue - COGS.
	measure 'Gross Profit' =
			VAR Ded = CALCULATE([Actual], Dim_Accounts[FSGroup] = "Deductions")
			VAR DedAbs = IF(ISBLANK(Ded), 0, ABS(Ded))
			RETURN
			[Revenue] - DedAbs - CALCULATE([Actual], Dim_Accounts[FSGroup] = "COGS")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: d77fa0d8-6e8d-4458-822f-2bbcd6da876f

	/// MATH FIX: reuses the now-corrected [Gross Profit] (which properly subtracts Deductions) instead of re-deriving Revenue-COGS-OPEX independently.
	measure EBITDA = [Gross Profit] - CALCULATE([Actual], Dim_Accounts[FSGroup] = "Operating Expenses")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 62a41958-b8e7-4d68-8053-5fd342289d9d

	measure EBIT =
			
			[EBITDA]
			- CALCULATE([Actual], Dim_Accounts[FSGroup] = "D&A")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 01df7a5e-2f2b-4ff0-834f-e0bf96689670

	/// MATH FIX: Financial Income/Expense carry native-negative raw signs (same root cause as the matrix bug), so the old raw signed FSGroup-level sum silently went the wrong direction. Now nets true magnitudes (Income - Expense) before adding to EBIT, matching the Income Statement matrix.
	measure 'Net Income' =
			VAR FinIncome = ABS(CALCULATE([Actual], Dim_Accounts[FSGroup] = "Financial Result", Dim_Accounts[FSSubgroup] = "Financial Income"))
			VAR FinExpense = ABS(CALCULATE([Actual], Dim_Accounts[FSGroup] = "Financial Result", Dim_Accounts[FSSubgroup] = "Financial Expenses"))
			VAR NetFin = FinIncome - FinExpense
			RETURN
			[EBIT] + NetFin - CALCULATE([Actual], Dim_Accounts[FSGroup] = "Taxes")
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 2eaf60d7-700a-4908-8e42-196bb679ab33

	measure 'FS Report Value' =
			
			VAR CurrentFS =
			    SELECTEDVALUE(INCOME_Structure[FSGroup])
			
			VAR CurrentSub =
			    SELECTEDVALUE(INCOME_Structure[FSSubgroup])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			
			    CurrentFS = "Gross Profit",
			        [Gross Profit],
			
			    CurrentFS = "EBITDA",
			        [EBITDA],
			
			    CurrentFS = "EBIT",
			        [EBIT],
			
			    CurrentFS = "Net Income",
			        [Net Income],
			
			    CALCULATE(
			        [Actual],
			
			        TREATAS(
			            {CurrentFS},
			            Dim_Accounts[FSGroup]
			        ),
			
			        TREATAS(
			            {CurrentSub},
			            Dim_Accounts[FSSubgroup]
			        )
			    )
			)
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: b72e2e7f-f3e9-41d3-96bb-563dcbed40cc

	/// Total Assets = Current + Non-Current. Composed from the same validated building blocks used elsewhere - guarantees internal consistency.
	measure BS_TotalAssets = [BS_CurrentAssets] + [BS_NonCurrentAssets]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: ebedb798-d0dc-4b99-ae4f-db9d932931bf

	/// Current Assets = Cash + AR + Inventory + Prepaid, each at true GL sign. CHANGED 2026-07-07: removed per-component ABS() that was masking a genuine negative-Inventory data anomaly as a phantom positive asset. See Management Report data quality note.
	measure BS_CurrentAssets =
			-- Components kept at their true GL-derived sign (no per-component ABS()).
			-- Cash, AR, and Prepaid are debit-normal and always non-negative in this GL,
			-- so this is a no-op for them. Inventory is intentionally NOT force-positive:
			-- a negative Inventory balance is a real GL/data anomaly (see Opening_Balances
			-- vs GL_Actual reconciliation note), and masking it with ABS() would convert a
			-- data error into a phantom asset instead of surfacing it.
			[BS_AsOf_Cash] + [CF_AsOf_AccountsReceivable] + [CF_AsOf_Inventory] + [CF_AsOf_PrepaidExpenses]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 714867f8-968c-4d71-88d5-cde518d3c8e7

	/// Non-Current Assets - now correctly month-aware.
	measure BS_NonCurrentAssets = [BS_AsOf_NonCurrentAssets]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: cb46384d-cbb3-43cb-aef0-a32e65e63605

	/// Cash - now correctly month-aware via BS_AsOf_Cash.
	measure BS_Cash = [BS_AsOf_Cash]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 7a94e03e-444d-483e-be48-6b8f57b03a48

	/// MATH FIX: was a naive lifetime cumulative SUM(GL_Actual[Amount]) with no opening-balance anchor, inflating to €231M. Now reuses the already-correct, OB-anchored CF_AsOf_AccountsReceivable (same approach validated in BS_2025/BS_2026).
	measure BS_AccountsReceivable = ABS([CF_AsOf_AccountsReceivable])
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 0584eab2-80ff-49ea-a127-f0334274cfa0

	/// MATH FIX: was a naive lifetime cumulative SUM(GL_Actual[Amount]) with no opening-balance anchor, inflating to €132.7M. Now reuses the already-correct, OB-anchored CF_AsOf_Inventory (same approach validated in BS_2025/BS_2026).
	measure BS_Inventory = ABS([CF_AsOf_Inventory])
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 5a7053cd-0b35-4e6d-b5fd-41a6dd2b70ed

	/// Total Liabilities = Current + Long-term. Composed from the same components as their individual measures - previously computed independently via a different GL filter, which caused the balance-check failure.
	measure BS_TotalLiabilities = [BS_CurrentLiabilities] + [BS_LongTermLiabilities]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: c4d67162-97a9-475c-ace8-ae4a051a9e07

	/// Current Liabilities = AP + Salaries Payable + Taxes Payable. ABS()-wrapped for correct Balance Sheet presentation (Liabilities always positive) - CF_AsOf_OtherCurrentLiabilities preserves raw sign for Cash Flow's own delta math.
	measure BS_CurrentLiabilities = ABS([CF_AsOf_OtherCurrentLiabilities])
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: c06afe6e-ba9d-4900-9678-e59b149ae5c9

	/// Long-term Liabilities - now correctly month-aware.
	measure BS_LongTermLiabilities = [BS_AsOf_LongTermLiabilities]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: b53b608f-3938-4980-ada0-05a98bb8532f

	/// Equity = Total Assets - Total Liabilities (accounting identity plug). CHANGED 2026-07-07: previously an independent OB-anchor + accrued-Net-Income roll-forward, which could diverge from Assets/Liabilities when GL and P&L don't fully reconcile mid-year. See Management Report data quality note for the April 2026 Inventory finding this surfaced.
	measure BS_Equity =
			-- Equity is derived as the balancing residual of the accounting identity
			-- (Assets = Liabilities + Equity), not as an independent NI roll-forward.
			-- Rationale: an independently-maintained roll-forward (prior anchor + accrued
			-- Net Income) is a second source of truth for the same number and can drift
			-- from Assets/Liabilities if the P&L feed and GL balance postings don't
			-- reconcile perfectly for an in-progress period. Deriving Equity as a plug
			-- guarantees BS_CheckBalance = 0 at every date, by construction.
			[BS_TotalAssets] - [BS_TotalLiabilities]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 4c969ea8-13bf-43a7-9b90-c21f3bfd120c

	/// Net Working Capital
	measure BS_NetWorkingCapital = [BS_CurrentAssets] - [BS_CurrentLiabilities]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 9654b768-3a77-41ad-a0b6-708104537792

	/// Current Ratio
	measure BS_CurrentRatio = DIVIDE([BS_CurrentAssets], [BS_CurrentLiabilities], BLANK())
		formatString: 0.00
		displayFolder: Balance Sheet\Ratios
		lineageTag: 7bad59ad-90a4-4e0c-803d-de33d0eced6d

	/// Quick Ratio - use ABS to ensure positive, protect against inventory > current assets
	measure BS_QuickRatio =
			VAR CA = [BS_CurrentAssets]
			VAR Inv = MIN([BS_Inventory], CA * 0.8)
			RETURN DIVIDE(CA - Inv, [BS_CurrentLiabilities], BLANK())
		formatString: 0.00
		displayFolder: Balance Sheet\Ratios
		lineageTag: 25f9a1ee-fac3-44b9-bac7-291eff8634ac

	/// Debt to Equity
	measure BS_DebtToEquity = DIVIDE([BS_TotalLiabilities], [BS_Equity], BLANK())
		formatString: 0.00
		displayFolder: Balance Sheet\Ratios
		lineageTag: 920d0af1-475e-4314-84ab-aabb53442d12

	/// Equity Ratio
	measure BS_EquityRatio = DIVIDE([BS_Equity], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: 52838187-7c3f-4fd9-b214-f4512c9d15d0

	/// Debt Ratio
	measure BS_DebtRatio = DIVIDE([BS_TotalLiabilities], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: eefd12b2-fdd1-4e26-bafe-288f42626702

	/// CHECK: Assets = Liabilities + Equity. Must = 0.
	measure BS_CheckBalance = [BS_TotalAssets] - [BS_TotalLiabilities] - [BS_Equity]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 9fca81ed-4792-4742-a32a-a206a3dbd000

	/// BS_ReportValue updated for new structure including Spacer rows
	measure BS_ReportValue =
			VAR SelYear   = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR YearEnd   = DATE(SelYear, 12, 31)
			VAR rowLevel  = SELECTEDVALUE(BS_Structure[RowLevel],    "")
			VAR acctName  = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR GL_Val = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader", "Spacer"} || acctName = "", BLANK(),
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: "€" #,0;-"€" #,0;-
		displayFolder: Balance Sheet
		lineageTag: 3654d42f-05e8-4339-9e62-d9870264f054

	/// IAS 7 Indirect Method: Net Income + D&A + Prepaid Expenses movement. Prepaid delta now uses period-start/period-end (MIN/MAX of selection) instead of DATEADD, so it aggregates correctly at any grain - month, year, or all-time.
	measure CF_OperatingCF =
			VAR NetIncome = [Net Income]
			VAR DA = CALCULATE([Actual], Dim_Accounts[FSGroup] = "D&A")
			VAR MinDate = MIN(Dim_Date[Date])
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR PriorDate = MinDate - 1
			VAR CurPre = CALCULATE([CF_AsOf_PrepaidExpenses], ALL(Dim_Date), Dim_Date[Date] = MaxDate)
			VAR PriorPre = CALCULATE([CF_AsOf_PrepaidExpenses], ALL(Dim_Date), Dim_Date[Date] = PriorDate)
			VAR PreChange = PriorPre - CurPre
			RETURN
			NetIncome + DA + PreChange
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: e3239313-b6b8-4919-928b-e6647ae57e87

	/// Investing CF = direct period sum of Machinery & Buildings GL postings (140100/140200), sign-corrected. Excludes 140300 Accumulated Depreciation - that's non-cash and already captured via the D&A add-back in Operating CF.
	measure CF_InvestingCF = -1 * CALCULATE(SUM(GL_Actual[Amount]), Dim_Accounts[Account] IN {"140100", "140200"})
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: be57bdcf-94c6-4711-bc29-ac40e61a6238

	/// Financing CF = direct period sum of Bank Loan & Lease Liability GL postings (230100/230200), sign-corrected.
	measure CF_FinancingCF = -1 * CALCULATE(SUM(GL_Actual[Amount]), Dim_Accounts[Account] IN {"230100", "230200"})
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 0876dde9-ba7e-452f-bb7c-eec05299750c

	/// Total net cash movement for the period
	measure CF_NetCashFlow = [CF_OperatingCF] + [CF_InvestingCF] + [CF_FinancingCF]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 2cbdf5cf-c406-40f1-bd86-44f9192e40d4

	/// Closing cash as of the day before the FIRST date in the current filter context. Correct at any grain - single month, full year, or all-time - unlike the prior EOMONTH(MAX(Date)) approach which only worked for single-month selections.
	measure CF_OpeningCash =
			VAR MinDate = MIN(Dim_Date[Date])
			VAR PriorDate = MinDate - 1
			RETURN CALCULATE([CF_ClosingCash], ALL(Dim_Date), Dim_Date[Date] = PriorDate)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: abeebb92-d999-41ec-8337-fb054dfab4de

	/// Closing cash = anchor + cumulative Net Income + D&A + Prepaid movement + Investing + Financing, from inception through the selected date. Uses ALL(Dim_Date)+explicit Date filter throughout (never Year/Month Number columns) to stay immune to slicer filter-conflict issues.
	measure CF_ClosingCash =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR EarliestDate = CALCULATE(MIN(Dim_Date[Date]), ALL(Dim_Date))
			VAR CumNetIncome = CALCULATE([Net Income], FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate))
			VAR CumDA = CALCULATE([Actual], Dim_Accounts[FSGroup] = "D&A", FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate))
			VAR InitialPrepaid = CALCULATE([CF_AsOf_PrepaidExpenses], ALL(Dim_Date), Dim_Date[Date] = EarliestDate)
			VAR CurPrepaid = CALCULATE([CF_AsOf_PrepaidExpenses], ALL(Dim_Date), Dim_Date[Date] = MaxDate)
			VAR PrepaidContribution = InitialPrepaid - CurPrepaid
			VAR CumInvesting = CALCULATE(-1 * SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate), Dim_Accounts[Account] IN {"140100", "140200"})
			VAR CumFinancing = CALCULATE(-1 * SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate), Dim_Accounts[Account] IN {"230100", "230200"})
			RETURN 1027823 + CumNetIncome + CumDA + PrepaidContribution + CumInvesting + CumFinancing
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 409a700e-c2ce-4898-bcdf-3a436ba6de02

	/// Cumulative closing cash balance for trend chart
	measure CF_RunningCash =
			CALCULATE(
			    [CF_ClosingCash],
			    FILTER(
			        ALL(Dim_Date),
			        Dim_Date[Date] <= MAX(Dim_Date[Date])
			    )
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 00984b8a-db48-46c5-98a0-e0a7829522eb

	/// Cash flow as % of revenue. Quality of earnings indicator.
	measure CF_OperatingMargin = DIVIDE([CF_OperatingCF], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Cash Flow\Ratios
		lineageTag: b913a786-a6aa-4c82-bf41-ff1b474f622f

	/// Operating CF available after investing. True cash generation.
	measure CF_FreeCashFlow = [CF_OperatingCF] + [CF_InvestingCF]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow\Ratios
		lineageTag: 477a97f5-ae7a-4e18-b5cf-86937efe7508

	/// Quality of earnings: CF vs Net Income. >1x = strong cash conversion. Format updated to show 'x' multiple, avoiding misreading as a percentage.
	measure CF_CashConversionRatio = DIVIDE([CF_OperatingCF], [Net Income], BLANK())
		formatString: 0.00"x"
		displayFolder: Cash Flow\Ratios
		lineageTag: 21c14914-b5ec-408b-852d-9aae019dbc7a

	/// Interest coverage: Operating CF / gross Financial (Interest) Expenses. Corrected to use gross expense, not net Financial Result - netting against Financial Income would overstate true debt-servicing capacity.
	measure CF_CashCoverageRatio =
			DIVIDE(
			    [CF_OperatingCF],
			    ABS([IS_FinancialExpenses]),
			    BLANK()
			)
		formatString: 0.00"x"
		displayFolder: Cash Flow\Ratios
		lineageTag: 9f0c148a-fc41-40ef-b8ee-653b02f4f183

	/// Context-aware value for CF matrix rows. Reads CF_Structure row context.
	measure CF_ReportValue =
			VAR grp = SELECTEDVALUE(CF_Structure[CFGroup])
			VAR line = SELECTEDVALUE(CF_Structure[LineItem])
			
			RETURN
			SWITCH(
			    TRUE(),
			    grp = "TOTAL OPERATING CF",   [CF_OperatingCF],
			    grp = "TOTAL INVESTING CF",   [CF_InvestingCF],
			    grp = "TOTAL FINANCING CF",   [CF_FinancingCF],
			    grp = "NET CASH FLOW",        [CF_NetCashFlow],
			    grp = "Opening Cash Balance", [CF_OpeningCash],
			    grp = "CLOSING CASH BALANCE", [CF_ClosingCash],
			    line = "Net Income",           [Net Income],
			    line = "Depreciation & Amortisation", CALCULATE([Actual], Dim_Accounts[FSGroup] = "D&A"),
			    line = "Impairments", BLANK(),
			    line = "Non-cash Provisions", BLANK(),
			    line = "Change in Accounts Receivable", BLANK(),
			    line = "Change in Inventory", BLANK(),
			    line = "Change in Other Current Liabilities", BLANK(),
			    line = "Change in Other Working Capital", (
			        CALCULATE([CF_AsOf_PrepaidExpenses], DATEADD(Dim_Date[Date], -1, MONTH))
			        - [CF_AsOf_PrepaidExpenses]
			    ),
			    line = "Change in Fixed Assets", [CF_InvestingCF],
			    line = "Change in Bank Loans", -1 * CALCULATE([Actual Amount], Dim_Accounts[Account] = "230100"),
			    line = "Change in Lease Liabilities", -1 * CALCULATE([Actual Amount], Dim_Accounts[Account] = "230200"),
			    BLANK()
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 8dc073ca-d75f-4e10-95be-579a1a810371

	/// Year-to-date Revenue
	measure IS_YTD_Revenue = CALCULATE([Revenue], DATESYTD(Dim_Date[Date]))
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: cacf1635-16fe-4937-967d-87bdf9d35205

	/// Month-to-date Revenue
	measure IS_MTD_Revenue = CALCULATE([Revenue], DATESMTD(Dim_Date[Date]))
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 93ebc976-2bae-423b-bf71-f51930b43137

	/// Year-to-date Net Income
	measure IS_YTD_NetIncome = CALCULATE([Net Income], DATESYTD(Dim_Date[Date]))
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 10099e02-9c8e-4785-95f1-0e9982ef35e1

	/// Year-to-date EBITDA
	measure IS_YTD_EBITDA = CALCULATE([EBITDA], DATESYTD(Dim_Date[Date]))
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 2bc54d4a-cff8-4a14-a2ce-3f953d42786e

	/// EBITDA as % of Revenue
	measure IS_EBITDAMargin = DIVIDE([EBITDA], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: 312a6c63-60e3-4139-bce0-3035ca4b519b

	/// Net Income as % of Revenue
	measure IS_NetMargin = DIVIDE([Net Income], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: 089402a0-adba-443f-b68c-cf854638817c

	/// Gross Profit as % of Revenue
	measure IS_GrossMargin = DIVIDE([Gross Profit], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: 15b87ad2-97c2-4774-a5ff-6c14ddb4c591

	/// YTD Revenue Budget
	measure IS_YTD_BudgetRevenue =
			CALCULATE(
			    [Budget],
			    DATESYTD(Dim_Date[Date]),
			    Dim_Accounts[FSGroup] = "Revenue"
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 464c953e-1067-41a5-98bc-49c48eef051b

	/// YTD Revenue variance vs budget
	measure IS_YTD_Variance = [IS_YTD_Revenue] - [IS_YTD_BudgetRevenue]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 4f610590-7819-46f8-a7e8-c6b9c6ddd0eb

	/// YTD Revenue variance % vs budget
	measure IS_YTD_Variance_Pct = DIVIDE([IS_YTD_Variance], ABS([IS_YTD_BudgetRevenue]), BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 317529ec-74b5-4a77-b5d1-61ddc4d3b6dc

	/// Revenue growth vs same period last year
	measure IS_RevenueVsPY =
			VAR CurPeriod = [Revenue]
			VAR PriorYear = CALCULATE([Revenue], SAMEPERIODLASTYEAR(Dim_Date[Date]))
			RETURN DIVIDE(CurPeriod - PriorYear, ABS(PriorYear), BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Time Intelligence
		lineageTag: 4bc9ce6e-1a99-41ad-915d-f26e04b85453

	/// Full-year revenue forecast based on YTD run rate — year-aware
	measure IS_Forecast =
			VAR SelYear = SELECTEDVALUE(Dim_Date[Year], YEAR(TODAY()))
			VAR MonthsWithData =
			    CALCULATE(
			        DISTINCTCOUNT(Dim_Date[Month Number]),
			        ALL(Dim_Date[Month Number]),
			        Dim_Date[Year] = SelYear
			    )
			VAR YTDRev =
			    CALCULATE(
			        [Revenue],
			        ALL(Dim_Date[Month Number]),
			        Dim_Date[Year] = SelYear
			    )
			RETURN
			IF(
			    MonthsWithData > 0 && MonthsWithData < 12,
			    DIVIDE(YTDRev, MonthsWithData) * 12,
			    YTDRev
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Forecast
		lineageTag: 5280c456-633b-40bb-a469-62ac3d70ce99

	/// Full-year forecast gap vs annual budget for selected year
	measure IS_ForecastVsBudget =
			VAR SelYear = SELECTEDVALUE(Dim_Date[Year], YEAR(TODAY()))
			VAR AnnualBudget =
			    CALCULATE(
			        [IS_RevenueBudget],
			        ALL(Dim_Date[Month Number]),
			        Dim_Date[Year] = SelYear
			    )
			RETURN [IS_Forecast] - AnnualBudget
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement\Forecast
		lineageTag: a487e7d3-bb6f-4f57-bff1-cff500d83f73

	/// Rank operating expense accounts for Top-5 cost driver visual. Use in visual filter: value <= 5
	measure IS_Top5CostDriverRank =
			RANKX(
			    ALL(Dim_Accounts[AccountName]),
			    CALCULATE(
			        [Actual],
			        Dim_Accounts[FSGroup] = "Operating Expenses"
			    ),
			    ,
			    DESC,
			    DENSE
			)
		displayFolder: Income Statement\Analytics
		lineageTag: e053f9a2-3ac2-4e91-82a5-c180e3db91e1

	/// Dynamic text commentary for Revenue KPI card
	measure IS_Commentary_Revenue =
			VAR VarPct = [IS_YTD_Variance_Pct]
			VAR Dir    = IF([IS_YTD_Variance] >= 0, "above", "below")
			VAR Icon   = IF([IS_YTD_Variance] >= 0, "▲", "▼")
			RETURN
			IF(
			    ISBLANK(VarPct),
			    "No budget data available.",
			    Icon & " Revenue is "
			    & FORMAT(ABS(VarPct), "0.0%")
			    & " " & Dir & " budget YTD ("
			    & FORMAT([IS_YTD_Revenue], "€ #,0")
			    & " vs " & FORMAT([IS_YTD_BudgetRevenue], "€ #,0") & ")"
			)
		displayFolder: Income Statement\Commentary
		lineageTag: 95d31c3f-a5d2-40a3-b6db-8a575dcbaecd

	/// Dynamic text commentary for EBITDA Margin KPI card
	measure IS_Commentary_EBITDA =
			VAR Margin    = [IS_EBITDAMargin]
			VAR BudMargin = DIVIDE(
			    CALCULATE([Budget], Dim_Accounts[FSGroup] IN {"Revenue","COGS","Operating Expenses"}),
			    CALCULATE([Budget], Dim_Accounts[FSGroup] = "Revenue"),
			    BLANK()
			)
			VAR Gap  = Margin - BudMargin
			VAR Icon = IF(Gap >= 0, "▲", "▼")
			RETURN
			IF(
			    ISBLANK(Margin),
			    "No data available.",
			    Icon & " EBITDA Margin: " & FORMAT(Margin, "0.0%")
			    & IF(NOT ISBLANK(BudMargin),
			        " (target " & FORMAT(BudMargin, "0.0%") & ", gap " & FORMAT(Gap, "+0.0%;-0.0%") & ")",
			        ""
			    )
			)
		displayFolder: Income Statement\Commentary
		lineageTag: f8e7754d-8d7e-4211-b548-898f78ef1d16

	/// Cumulative GL amount for assets up to max selected date
	measure BS_CumulativeActual_Asset =
			CALCULATE(
			    [Actual Amount] * -1,
			    FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date]))
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\_Base
		lineageTag: 6a957f78-f0fd-4839-a136-54eb3d9724ff

	/// Cumulative actual for specific account type up to max date
	measure BS_GL_Assets =
			CALCULATE(
			    [Actual Amount] * -1,
			    FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])),
			    Dim_Accounts[AccountType] = "Asset"
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\_Base
		lineageTag: 42a72c7c-ac17-4588-848b-963af3a1fab2

	/// Cumulative GL liabilities up to max date (credit=positive)
	measure BS_GL_Liabilities =
			CALCULATE(
			    [Actual Amount],
			    FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])),
			    Dim_Accounts[AccountType] = "Liability"
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\_Base
		lineageTag: 70e816ea-5517-45d5-b52e-17c6fabbfc5f

	/// Cumulative GL equity up to max date
	measure BS_GL_Equity =
			CALCULATE(
			    [Actual Amount],
			    FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])),
			    Dim_Accounts[AccountType] = "Equity"
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\_Base
		lineageTag: 6d17b714-604c-4a97-a8d6-3eb44b5cb0e8

	/// Cumulative Net Income up to max selected date
	measure BS_CumulativeNetIncome =
			CALCULATE(
			    [Net Income],
			    FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date]))
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\_Base
		lineageTag: ec984c2e-dfca-4f8b-b2f2-8624c6c25299

	/// JSON for KPI cards. All values as dot-decimal strings.
	measure KPI_Cards_JSON =
			VAR vRev  = SUBSTITUTE(FORMAT([Revenue],     "#,##0"), ",", ".")
			VAR vGP   = SUBSTITUTE(FORMAT([Gross Profit], "#,##0"), ",", ".")
			VAR vEB   = SUBSTITUTE(FORMAT([EBITDA],       "#,##0"), ",", ".")
			VAR vET   = SUBSTITUTE(FORMAT([EBIT],         "#,##0"), ",", ".")
			VAR vNI   = SUBSTITUTE(FORMAT([Net Income],   "#,##0"), ",", ".")
			RETURN
			"{" &
			  """Revenue"":"    & """" & vRev & """" & "," &
			  """GrossProfit"":" & """" & vGP  & """" & "," &
			  """EBITDA"":"     & """" & vEB  & """" & "," &
			  """EBIT"":"       & """" & vET  & """" & "," &
			  """NetIncome"":"  & """" & vNI  & """" &
			"}"
		displayFolder: JSON Measures
		lineageTag: e177b353-15d9-4942-b296-f1212f9a59bf

	/// JSON for Revenue Trend chart. Monthly data for selected year.
	measure RevenueTrend_JSON =
			VAR SelYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        FILTER(
			            ALL(Dim_Date[Month Number], Dim_Date[MonthShort]),
			            NOT ISBLANK(Dim_Date[Month Number])
			        ),
			        "Rev",
			        CALCULATE([Revenue], Dim_Date[Year] = SelYear)
			    )
			VAR tblFiltered = FILTER(tbl, NOT ISBLANK([Rev]))
			VAR monthLabels =
			    CONCATENATEX(
			        tblFiltered,
			        Q & Dim_Date[MonthShort] & Q,
			        ",",
			        Dim_Date[Month Number], ASC
			    )
			VAR monthValues =
			    CONCATENATEX(
			        tblFiltered,
			        Q & SUBSTITUTE(FORMAT([Rev], "#,##0"), ",", ".") & Q,
			        ",",
			        Dim_Date[Month Number], ASC
			    )
			RETURN
			"{" &
			  """months"":[" & monthLabels & "]," &
			  """values"":[" & monthValues & "]" &
			"}"
		displayFolder: JSON Measures
		lineageTag: a5da42fc-48c2-473d-bbf6-31b38204c501

	/// JSON for EBITDA vs Net Income chart. Monthly data for selected year.
	measure EBITDA_vs_NetIncome_JSON =
			VAR SelYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        FILTER(
			            ALL(Dim_Date[Month Number], Dim_Date[MonthShort]),
			            NOT ISBLANK(Dim_Date[Month Number])
			        ),
			        "EB", CALCULATE([EBITDA],    Dim_Date[Year] = SelYear),
			        "NI", CALCULATE([Net Income], Dim_Date[Year] = SelYear)
			    )
			VAR tblF = FILTER(tbl, NOT ISBLANK([EB]))
			VAR monthLabels = CONCATENATEX(tblF, Q & Dim_Date[MonthShort] & Q, ",", Dim_Date[Month Number], ASC)
			VAR ebitdaVals  = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([EB], "#,##0"), ",", ".") & Q, ",", Dim_Date[Month Number], ASC)
			VAR niVals      = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([NI], "#,##0"), ",", ".") & Q, ",", Dim_Date[Month Number], ASC)
			RETURN
			"{" &
			  """months"":["  & monthLabels & "]," &
			  """ebitda"":["  & ebitdaVals  & "]," &
			  """netincome"":[" & niVals    & "]" &
			"}"
		displayFolder: JSON Measures
		lineageTag: 0289fd5d-8867-47ba-b716-27055e82d40a

	/// JSON for Expense Breakdown donut chart.
	measure ExpenseBreakdown_JSON =
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        FILTER(
			            ALL(Dim_Accounts[FSSubgroup]),
			            Dim_Accounts[FSSubgroup] IN {
			                "Personnel", "Administrative",
			                "Facilities", "Commercial", "Technology"
			            }
			        ),
			        "Val", CALCULATE([Actual], Dim_Accounts[FSGroup] = "Operating Expenses")
			    )
			VAR labelsList = CONCATENATEX(tbl, Q & Dim_Accounts[FSSubgroup] & Q, ",")
			VAR valsList   = CONCATENATEX(tbl, Q & SUBSTITUTE(FORMAT([Val], "#,##0"), ",", ".") & Q, ",")
			RETURN
			"{" &
			  """labels"":[" & labelsList & "]," &
			  """values"":[" & valsList   & "]" &
			"}"
		displayFolder: JSON Measures
		lineageTag: 4f91cbcc-bef1-4835-aae2-d52b7ec5ff48

	/// JSON for Income Statement matrix table. Monthly columns, 6 P&L rows.
	measure IncomeStatementMatrix_JSON =
			VAR SelYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        FILTER(
			            ALL(Dim_Date[Month Number], Dim_Date[MonthShort]),
			            NOT ISBLANK(Dim_Date[Month Number])
			        ),
			        "vRev", CALCULATE([Revenue],      Dim_Date[Year] = SelYear),
			        "vCOG", CALCULATE(CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS"), Dim_Date[Year] = SelYear),
			        "vOpX", CALCULATE(CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses"), Dim_Date[Year] = SelYear),
			        "vEB",  CALCULATE([EBITDA],        Dim_Date[Year] = SelYear),
			        "vET",  CALCULATE([EBIT],          Dim_Date[Year] = SelYear),
			        "vNI",  CALCULATE([Net Income],    Dim_Date[Year] = SelYear)
			    )
			VAR tblF = FILTER(tbl, NOT ISBLANK([vRev]))
			VAR mths = CONCATENATEX(tblF, Q & Dim_Date[MonthShort] & Q, ",", Dim_Date[Month Number], ASC)
			VAR rRev = Q & "Revenue"             & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vRev],"#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			VAR rCOG = Q & "COGS"                & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vCOG],"#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			VAR rOpX = Q & "Operating Expenses"  & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vOpX],"#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			VAR rEB  = Q & "EBITDA"              & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vEB], "#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			VAR rET  = Q & "EBIT"                & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vET], "#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			VAR rNI  = Q & "Net Income"          & Q & ":[" & CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vNI], "#,##0"),",",".") & Q, ",", Dim_Date[Month Number], ASC) & "]"
			RETURN
			"{" &
			  """months"":[" & mths & "]," &
			  """rows"":[" &
			    "{""name"":" & rRev & "}," &
			    "{""name"":" & rCOG & "}," &
			    "{""name"":" & rOpX & "}," &
			    "{""name"":" & rEB  & "}," &
			    "{""name"":" & rET  & "}," &
			    "{""name"":" & rNI  & "}" &
			  "]" &
			"}"
		displayFolder: JSON Measures
		lineageTag: 30ccb6d3-e315-4b49-83a0-cd965baaced6

	/// Executive Summary KPI block - Revenue, EBITDA, Net Income, Total Assets, Cash, Operating CF with YoY deltas
	measure ES_KPI_JSON =
			VAR Q = """"
			VAR SelYear   = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR PrevYear  = SelYear - 1
			
			VAR vRev      = [Revenue]
			VAR vRevPY    = CALCULATE([Revenue],   Dim_Date[Year] = PrevYear)
			VAR vRevDelta = IF(vRevPY <> 0, DIVIDE(vRev - vRevPY, ABS(vRevPY)), BLANK())
			
			VAR vEB       = [EBITDA]
			VAR vEBPY     = CALCULATE([EBITDA],    Dim_Date[Year] = PrevYear)
			VAR vEBDelta  = IF(vEBPY <> 0, DIVIDE(vEB - vEBPY, ABS(vEBPY)), BLANK())
			
			VAR vNI       = [Net Income]
			VAR vNIPY     = CALCULATE([Net Income],Dim_Date[Year] = PrevYear)
			VAR vNIDelta  = IF(vNIPY <> 0, DIVIDE(vNI - vNIPY, ABS(vNIPY)), BLANK())
			
			VAR vAssets   = [BS_TotalAssets]
			VAR vCash     = [BS_Cash]
			VAR vEquity   = [BS_Equity]
			VAR vLiab     = [BS_TotalLiabilities]
			
			VAR vOCF      = [CF_OperatingCF]
			VAR vFCF      = [CF_FreeCashFlow]
			
			VAR vGM       = [IS_GrossMargin]
			VAR vEM       = [IS_EBITDAMargin]
			VAR vNM       = [IS_NetMargin]
			
			VAR vVAR      = [VAR]
			VAR vVARpct   = [VAR %]
			
			VAR vCR       = [BS_CurrentRatio]
			VAR vDE       = [BS_DebtToEquity]
			
			VAR fmt = "#,##0"
			VAR fmtPct = "0.0%"
			
			RETURN
			"{" &
			  Q & "year"        & Q & ":"  & SelYear & "," &
			  Q & "revenue"     & Q & ":"  & Q & SUBSTITUTE(FORMAT(vRev,  fmt),",",".") & Q & "," &
			  Q & "revDelta"    & Q & ":"  & Q & FORMAT(vRevDelta, "0.0%") & Q & "," &
			  Q & "ebitda"      & Q & ":"  & Q & SUBSTITUTE(FORMAT(vEB,   fmt),",",".") & Q & "," &
			  Q & "ebitdaDelta" & Q & ":"  & Q & FORMAT(vEBDelta,  "0.0%") & Q & "," &
			  Q & "netIncome"   & Q & ":"  & Q & SUBSTITUTE(FORMAT(vNI,   fmt),",",".") & Q & "," &
			  Q & "niDelta"     & Q & ":"  & Q & FORMAT(vNIDelta,  "0.0%") & Q & "," &
			  Q & "totalAssets" & Q & ":"  & Q & SUBSTITUTE(FORMAT(vAssets,fmt),",",".") & Q & "," &
			  Q & "cash"        & Q & ":"  & Q & SUBSTITUTE(FORMAT(vCash,  fmt),",",".") & Q & "," &
			  Q & "equity"      & Q & ":"  & Q & SUBSTITUTE(FORMAT(vEquity,fmt),",",".") & Q & "," &
			  Q & "liabilities" & Q & ":"  & Q & SUBSTITUTE(FORMAT(vLiab,  fmt),",",".") & Q & "," &
			  Q & "operatingCF" & Q & ":"  & Q & SUBSTITUTE(FORMAT(vOCF,  fmt),",",".") & Q & "," &
			  Q & "freeCashFlow"& Q & ":"  & Q & SUBSTITUTE(FORMAT(vFCF,  fmt),",",".") & Q & "," &
			  Q & "grossMargin" & Q & ":"  & Q & FORMAT(vGM, "0.0%") & Q & "," &
			  Q & "ebitdaMargin"& Q & ":"  & Q & FORMAT(vEM, "0.0%") & Q & "," &
			  Q & "netMargin"   & Q & ":"  & Q & FORMAT(vNM, "0.0%") & Q & "," &
			  Q & "budgetVAR"   & Q & ":"  & Q & SUBSTITUTE(FORMAT(vVAR, fmt),",",".") & Q & "," &
			  Q & "budgetVARpct"& Q & ":"  & Q & FORMAT(vVARpct, "0.0%") & Q & "," &
			  Q & "currentRatio"& Q & ":"  & Q & FORMAT(vCR, "0.00") & Q & "," &
			  Q & "debtToEquity"& Q & ":"  & Q & FORMAT(vDE, "0.00") & Q &
			"}"
		displayFolder: JSON Measures
		lineageTag: 9ff46dbd-789f-499d-81bb-cdccbe535f23

	/// Budget vs Actual waterfall data by year for Executive Summary
	measure ES_WaterfallBVA_JSON =
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        SUMMARIZE(ALL(Dim_Date), Dim_Date[Year]),
			        "vAct", CALCULATE([Revenue], ALL(Dim_Date[Month Number], Dim_Date[MonthShort])),
			        "vBud", CALCULATE([Budget],  ALL(Dim_Date[Month Number], Dim_Date[MonthShort]))
			    )
			VAR tblF = FILTER(tbl, NOT ISBLANK([vAct]) && Dim_Date[Year] >= 2023)
			VAR yrs  = CONCATENATEX(tblF, Q & FORMAT(Dim_Date[Year],"0") & Q, ",", Dim_Date[Year], ASC)
			VAR acts = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vAct],"#,##0"),",",".") & Q, ",", Dim_Date[Year], ASC)
			VAR buds = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vBud],"#,##0"),",",".") & Q, ",", Dim_Date[Year], ASC)
			RETURN
			"{" &
			  Q & "years"   & Q & ":[" & yrs  & "]," &
			  Q & "actual"  & Q & ":[" & acts & "]," &
			  Q & "budget"  & Q & ":[" & buds & "]"
			& "}"
		displayFolder: JSON Measures
		lineageTag: cab043d8-2ab6-49db-94a1-32b998d4341d

	/// Balance Sheet snapshot for Executive Summary - Assets, Liabilities, Equity by year
	measure ES_BSSnapshot_JSON =
			VAR Q = """"
			VAR tbl =
			    ADDCOLUMNS(
			        SUMMARIZE(ALL(Dim_Date), Dim_Date[Year]),
			        "vA",  CALCULATE([BS_TotalAssets]),
			        "vL",  CALCULATE([BS_TotalLiabilities]),
			        "vE",  CALCULATE([BS_Equity])
			    )
			VAR tblF = FILTER(tbl, NOT ISBLANK([vA]) && Dim_Date[Year] >= 2023)
			VAR yrs  = CONCATENATEX(tblF, Q & FORMAT(Dim_Date[Year],"0") & Q, ",", Dim_Date[Year], ASC)
			VAR aVals = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vA],"#,##0"),",",".") & Q, ",", Dim_Date[Year], ASC)
			VAR lVals = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vL],"#,##0"),",",".") & Q, ",", Dim_Date[Year], ASC)
			VAR eVals = CONCATENATEX(tblF, Q & SUBSTITUTE(FORMAT([vE],"#,##0"),",",".") & Q, ",", Dim_Date[Year], ASC)
			RETURN
			"{" &
			  Q & "years"       & Q & ":[" & yrs   & "]," &
			  Q & "assets"      & Q & ":[" & aVals & "]," &
			  Q & "liabilities" & Q & ":[" & lVals & "]," &
			  Q & "equity"      & Q & ":[" & eVals & "]"
			& "}"
		displayFolder: JSON Measures
		lineageTag: 3b33b210-7504-4066-ad43-f02e8bbe0c81

	/// Executive Summary HTML page - full CFO-level dashboard rendered via HTML Content visual
	measure ES_HTML =
			VAR Q = """"
			VAR SelYear   = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR PrevYear  = SelYear - 1
			
			VAR vRev      = [Revenue]
			VAR vRevPY    = CALCULATE([Revenue],    Dim_Date[Year] = PrevYear)
			VAR vRevGrw   = DIVIDE(vRev - vRevPY, ABS(vRevPY), BLANK())
			
			VAR vEB       = [EBITDA]
			VAR vEBM      = [IS_EBITDAMargin]
			VAR vEBPY     = CALCULATE([EBITDA],    Dim_Date[Year] = PrevYear)
			VAR vEBGrw    = DIVIDE(vEB - vEBPY, ABS(vEBPY), BLANK())
			
			VAR vNI       = [Net Income]
			VAR vNIM      = [IS_NetMargin]
			VAR vNIPY     = CALCULATE([Net Income], Dim_Date[Year] = PrevYear)
			VAR vNIGrw    = DIVIDE(vNI - vNIPY, ABS(vNIPY), BLANK())
			
			VAR vGM       = [IS_GrossMargin]
			VAR vAssets   = [BS_TotalAssets]
			VAR vCash     = [BS_Cash]
			VAR vEquity   = [BS_Equity]
			VAR vLiab     = [BS_TotalLiabilities]
			VAR vOCF      = [CF_OperatingCF]
			VAR vFCF      = [CF_FreeCashFlow]
			VAR vCR       = [BS_CurrentRatio]
			VAR vDE       = [BS_DebtToEquity]
			VAR vVAR      = [VAR]
			VAR vVARpct   = [VAR %]
			VAR vBud      = [Budget]
			
			VAR fmt = "#,##0"
			
			VAR sRev    = SUBSTITUTE(FORMAT(vRev,    fmt), ",", ".")
			VAR sEB     = SUBSTITUTE(FORMAT(vEB,     fmt), ",", ".")
			VAR sNI     = SUBSTITUTE(FORMAT(vNI,     fmt), ",", ".")
			VAR sAssets = SUBSTITUTE(FORMAT(vAssets, fmt), ",", ".")
			VAR sCash   = SUBSTITUTE(FORMAT(vCash,   fmt), ",", ".")
			VAR sOCF    = SUBSTITUTE(FORMAT(vOCF,    fmt), ",", ".")
			VAR sFCF    = SUBSTITUTE(FORMAT(vFCF,    fmt), ",", ".")
			VAR sVAR    = SUBSTITUTE(FORMAT(vVAR,    fmt), ",", ".")
			VAR sBud    = SUBSTITUTE(FORMAT(vBud,    fmt), ",", ".")
			VAR sCR     = FORMAT(vCR,   "0.00")
			VAR sDE     = FORMAT(vDE,   "0.00")
			VAR sGM     = FORMAT(vGM,   "0.0%")
			VAR sEM     = FORMAT(vEBM,  "0.0%")
			VAR sNM     = FORMAT(vNIM,  "0.0%")
			VAR sVARpct = FORMAT(vVARpct, "+0.0%;-0.0%")
			VAR sRevGrw = FORMAT(vRevGrw, "+0.0%;-0.0%")
			VAR sEBGrw  = FORMAT(vEBGrw,  "+0.0%;-0.0%")
			VAR sNIGrw  = FORMAT(vNIGrw,  "+0.0%;-0.0%")
			
			VAR niColor  = IF(vNI  >= 0, "#4CAF50", "#C00000")
			VAR varColor = IF(vVAR >= 0, "#4CAF50", "#C00000")
			VAR ocfColor = IF(vOCF >= 0, "#4CAF50", "#C00000")
			VAR revArrow = IF(vRevGrw >= 0, "▲", "▼")
			VAR ebArrow  = IF(vEBGrw  >= 0, "▲", "▼")
			VAR niArrow  = IF(vNIGrw  >= 0, "▲", "▼")
			VAR varArrow = IF(vVAR    >= 0, "▲", "▼")
			
			VAR commentary = [IS_Commentary_Revenue]
			
			RETURN
			"<style>
			  *{margin:0;padding:0;box-sizing:border-box;font-family:'Segoe UI',sans-serif}
			  body{background:#000;color:#fff;padding:10px;height:100vh;overflow:hidden}
			  .header{display:flex;align-items:center;justify-content:space-between;padding:6px 12px;border-bottom:1px solid #C00000;margin-bottom:10px}
			  .header h1{font-size:14px;font-weight:700;letter-spacing:2px;color:#fff;text-transform:uppercase}
			  .header .period{font-size:11px;color:#aaa;letter-spacing:1px}
			  .header .entity{font-size:11px;color:#C00000;font-weight:600;letter-spacing:1px}
			  .grid{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin-bottom:8px}
			  .kpi{background:#111;border:1px solid #222;border-radius:4px;padding:8px 10px;position:relative;overflow:hidden}
			  .kpi::before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:#C00000}
			  .kpi-label{font-size:9px;color:#888;text-transform:uppercase;letter-spacing:1px;margin-bottom:2px}
			  .kpi-value{font-size:14px;font-weight:700;color:#fff;letter-spacing:-0.5px}
			  .kpi-delta{font-size:9px;margin-top:2px;font-weight:600}
			  .kpi-sub{font-size:9px;color:#666;margin-top:1px}
			  .section-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-bottom:8px}
			  .panel{background:#111;border:1px solid #222;border-radius:4px;padding:10px}
			  .panel-title{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#C00000;border-bottom:1px solid #1a1a1a;padding-bottom:4px;margin-bottom:8px}
			  .ratio-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px}
			  .ratio-item{padding:5px 7px;background:#0a0a0a;border-radius:3px;border-left:2px solid #333}
			  .ratio-label{font-size:8px;color:#666;text-transform:uppercase;letter-spacing:0.8px}
			  .ratio-value{font-size:13px;font-weight:700;color:#fff;margin-top:1px}
			  .bva-row{display:flex;align-items:center;justify-content:space-between;padding:4px 0;border-bottom:1px solid #1a1a1a;font-size:10px}
			  .bva-label{color:#888;width:70px}
			  .bva-bar-wrap{flex:1;margin:0 8px;height:6px;background:#1a1a1a;border-radius:3px;overflow:hidden}
			  .bva-bar{height:100%;border-radius:3px}
			  .bva-val{color:#fff;font-weight:600;min-width:60px;text-align:right;font-size:9px}
			  .cf-item{display:flex;justify-content:space-between;align-items:center;padding:4px 0;border-bottom:1px solid #111;font-size:10px}
			  .cf-label{color:#888}
			  .cf-val{font-weight:600}
			  .commentary{background:#0a0a0a;border:1px solid #1a1a1a;border-left:3px solid #C00000;border-radius:3px;padding:6px 10px;font-size:9px;color:#aaa;line-height:1.5}
			  .green{color:#4CAF50}.red{color:#C00000}.white{color:#fff}
			  .full-row{grid-column:1/-1}
			</style>
			<body>
			  <div class='header'>
			    <div>
			      <div class='entity'>CC MODEL SA — IT01</div>
			      <h1>Executive Summary</h1>
			    </div>
			    <div class='period'>FY " & FORMAT(SelYear,"0") & " &nbsp;|&nbsp; Jan 2023 – Apr 2026</div>
			  </div>
			
			  <div class='grid'>
			    <div class='kpi'>
			      <div class='kpi-label'>Revenue</div>
			      <div class='kpi-value'>€ " & sRev & "</div>
			      <div class='kpi-delta' style='color:" & IF(vRevGrw>=0,"#4CAF50","#C00000") & "'>" & revArrow & " " & sRevGrw & " vs PY</div>
			      <div class='kpi-sub'>Gross Margin: " & sGM & "</div>
			    </div>
			    <div class='kpi'>
			      <div class='kpi-label'>EBITDA</div>
			      <div class='kpi-value'>€ " & sEB & "</div>
			      <div class='kpi-delta' style='color:" & IF(vEBGrw>=0,"#4CAF50","#C00000") & "'>" & ebArrow & " " & sEBGrw & " vs PY</div>
			      <div class='kpi-sub'>Margin: " & sEM & "</div>
			    </div>
			    <div class='kpi'>
			      <div class='kpi-label'>Net Income</div>
			      <div class='kpi-value' style='color:" & niColor & "'>€ " & sNI & "</div>
			      <div class='kpi-delta' style='color:" & IF(vNIGrw>=0,"#4CAF50","#C00000") & "'>" & niArrow & " " & sNIGrw & " vs PY</div>
			      <div class='kpi-sub'>Net Margin: " & sNM & "</div>
			    </div>
			    <div class='kpi'>
			      <div class='kpi-label'>Total Assets</div>
			      <div class='kpi-value'>€ " & sAssets & "</div>
			      <div class='kpi-delta' style='color:#888'>Equity: € " & SUBSTITUTE(FORMAT(vEquity,fmt),",",".") & "</div>
			      <div class='kpi-sub'>Liabilities: € " & SUBSTITUTE(FORMAT(vLiab,fmt),",",".") & "</div>
			    </div>
			    <div class='kpi'>
			      <div class='kpi-label'>Cash Balance</div>
			      <div class='kpi-value'>€ " & sCash & "</div>
			      <div class='kpi-delta' style='color:" & ocfColor & "'>OCF: € " & sOCF & "</div>
			      <div class='kpi-sub'>FCF: € " & sFCF & "</div>
			    </div>
			    <div class='kpi'>
			      <div class='kpi-label'>Budget Variance</div>
			      <div class='kpi-value' style='color:" & varColor & "'>€ " & sVAR & "</div>
			      <div class='kpi-delta' style='color:" & varColor & "'>" & varArrow & " " & sVARpct & " vs Budget</div>
			      <div class='kpi-sub'>Budget: € " & sBud & "</div>
			    </div>
			  </div>
			
			  <div class='section-row'>
			    <div class='panel'>
			      <div class='panel-title'>Financial Ratios</div>
			      <div class='ratio-grid'>
			        <div class='ratio-item'><div class='ratio-label'>Current Ratio</div><div class='ratio-value' style='color:" & IF(vCR>=1.5,"#4CAF50","#C00000") & "'>" & sCR & "</div></div>
			        <div class='ratio-item'><div class='ratio-label'>Debt / Equity</div><div class='ratio-value' style='color:" & IF(vDE<=1,"#4CAF50","#C00000") & "'>" & sDE & "</div></div>
			        <div class='ratio-item'><div class='ratio-label'>Gross Margin</div><div class='ratio-value'>" & sGM & "</div></div>
			        <div class='ratio-item'><div class='ratio-label'>EBITDA Margin</div><div class='ratio-value'>" & sEM & "</div></div>
			        <div class='ratio-item'><div class='ratio-label'>Net Margin</div><div class='ratio-value' style='color:" & IF(vNIM>=0,"#4CAF50","#C00000") & "'>" & sNM & "</div></div>
			        <div class='ratio-item'><div class='ratio-label'>OCF Margin</div><div class='ratio-value' style='color:" & IF(vOCF>=0,"#4CAF50","#C00000") & "'>" & FORMAT(DIVIDE(vOCF,vRev),"0.0%") & "</div></div>
			      </div>
			    </div>
			
			    <div class='panel'>
			      <div class='panel-title'>Budget vs Actual</div>
			      <div class='bva-row'>
			        <div class='bva-label'>Actual</div>
			        <div class='bva-bar-wrap'><div class='bva-bar' style='width:90%;background:#C00000'></div></div>
			        <div class='bva-val'>€ " & sRev & "</div>
			      </div>
			      <div class='bva-row'>
			        <div class='bva-label'>Budget</div>
			        <div class='bva-bar-wrap'><div class='bva-bar' style='width:" & FORMAT(DIVIDE(vBud,vRev)*90,"0") & "%;background:#555'></div></div>
			        <div class='bva-val'>€ " & sBud & "</div>
			      </div>
			      <div class='bva-row' style='border:none;margin-top:4px'>
			        <div class='bva-label'>Variance</div>
			        <div class='bva-bar-wrap'></div>
			        <div class='bva-val' style='color:" & varColor & "'>" & sVARpct & "</div>
			      </div>
			      <div style='margin-top:6px;padding-top:6px;border-top:1px solid #1a1a1a'>
			        <div class='commentary'>" & commentary & "</div>
			      </div>
			    </div>
			
			    <div class='panel'>
			      <div class='panel-title'>Cash Flow Summary</div>
			      <div class='cf-item'><div class='cf-label'>Operating CF</div><div class='cf-val' style='color:" & ocfColor & "'>€ " & sOCF & "</div></div>
			      <div class='cf-item'><div class='cf-label'>Investing CF</div><div class='cf-val' style='color:#aaa'>€ " & SUBSTITUTE(FORMAT([CF_InvestingCF],fmt),",",".") & "</div></div>
			      <div class='cf-item'><div class='cf-label'>Financing CF</div><div class='cf-val' style='color:#aaa'>€ " & SUBSTITUTE(FORMAT([CF_FinancingCF],fmt),",",".") & "</div></div>
			      <div class='cf-item' style='border-bottom:1px solid #C00000;padding-bottom:5px;margin-bottom:4px'>
			        <div class='cf-label'>Net Cash Flow</div>
			        <div class='cf-val' style='color:" & IF([CF_NetCashFlow]>=0,"#4CAF50","#C00000") & "'>€ " & SUBSTITUTE(FORMAT([CF_NetCashFlow],fmt),",",".") & "</div>
			      </div>
			      <div class='cf-item'><div class='cf-label' style='color:#C00000;font-weight:700'>Closing Cash</div><div class='cf-val' style='color:#fff;font-size:12px'>€ " & SUBSTITUTE(FORMAT([CF_ClosingCash],fmt),",",".") & "</div></div>
			      <div class='cf-item'><div class='cf-label'>Free Cash Flow</div><div class='cf-val' style='color:" & IF(vFCF>=0,"#4CAF50","#C00000") & "'>€ " & sFCF & "</div></div>
			    </div>
			  </div>
			</body>"
		displayFolder: JSON Measures
		lineageTag: 50bd0b0a-ce4f-4cbd-82b1-8f897376623f

	/// Days Sales Outstanding
	measure BS_DSO = DIVIDE([BS_AccountsReceivable], [Revenue] / 365, BLANK())
		formatString: 0.0
		displayFolder: Balance Sheet\Working Capital
		lineageTag: a544287a-c80c-4d0d-9056-6496b5463de2

	/// Days Payable Outstanding
	measure BS_DPO = DIVIDE([BS_CurrentLiabilities], CALCULATE([Actual], Dim_Accounts[FSGroup] = "COGS") / 365, BLANK())
		formatString: 0.0
		displayFolder: Balance Sheet\Working Capital
		lineageTag: 626594fb-2e3e-4689-a0b9-bd23f54dc977

	/// Net Debt — Total Liabilities minus Cash
	measure BS_NetDebt = [BS_TotalLiabilities] - [BS_Cash]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\Working Capital
		lineageTag: 31bfcbfe-7cc6-4245-a2b5-dd0c380147dd

	/// NWC as % of Total Assets
	measure BS_NWC_Pct = DIVIDE([BS_NetWorkingCapital], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Working Capital
		lineageTag: c6f178e3-e18e-4404-93f3-fe442a19a87d

	/// Total Assets prior year
	measure BS_TotalAssets_PY = VAR PrevYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year])) - 1 RETURN CALCULATE([BS_TotalAssets], Dim_Date[Year] = PrevYear)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\YoY
		lineageTag: 42c4ef58-2742-40c9-ad6d-c82fea524726

	/// Total Assets YoY growth %
	measure BS_TotalAssets_YoY = DIVIDE([BS_TotalAssets] - [BS_TotalAssets_PY], ABS([BS_TotalAssets_PY]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Balance Sheet\YoY
		lineageTag: 21d67132-edc8-42d4-a42f-17ce55d8ddc8

	/// Total Liabilities prior year
	measure BS_TotalLiabilities_PY = VAR PrevYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year])) - 1 RETURN CALCULATE([BS_TotalLiabilities], Dim_Date[Year] = PrevYear)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\YoY
		lineageTag: 9601a9cd-fc6f-4086-ac91-30a525c6e844

	/// Total Liabilities YoY change %
	measure BS_TotalLiabilities_YoY = DIVIDE([BS_TotalLiabilities] - [BS_TotalLiabilities_PY], ABS([BS_TotalLiabilities_PY]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Balance Sheet\YoY
		lineageTag: 104e42fe-a1eb-480b-bd11-edd9ff3d2834

	/// Equity prior year
	measure BS_Equity_PY = VAR PrevYear = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year])) - 1 RETURN CALCULATE([BS_Equity], Dim_Date[Year] = PrevYear)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\YoY
		lineageTag: 9e1c1517-49cc-4d3c-830e-b869c23a1f5d

	/// Equity YoY growth %
	measure BS_Equity_YoY = DIVIDE([BS_Equity] - [BS_Equity_PY], ABS([BS_Equity_PY]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Balance Sheet\YoY
		lineageTag: 0ed2e99f-79af-47e2-8e65-53725d08e16f

	/// Current Assets as % of Total Assets
	measure BS_CurrentAssets_Pct = DIVIDE([BS_CurrentAssets], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: d24157fa-c440-4e5d-a9ca-af158a831a4c

	/// Non-current Assets as % of Total Assets
	measure BS_NonCurrentAssets_Pct = DIVIDE([BS_NonCurrentAssets], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: 2073205e-dda6-4a10-9cec-3c6ff55e5b2c

	/// Current Liabilities as % of Total Assets
	measure BS_CurrentLiabilities_Pct = DIVIDE([BS_CurrentLiabilities], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: 33816104-baf5-4fde-9e9b-d1347e16b598

	/// Long-term Liabilities as % of Total Assets
	measure BS_LongTermLiabilities_Pct = DIVIDE([BS_LongTermLiabilities], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: b2b405c3-e17f-4cc0-b329-3a7c2227b325

	/// Equity as % of Total Assets
	measure BS_Equity_Pct = DIVIDE([BS_Equity], [BS_TotalAssets], BLANK())
		formatString: 0.0%
		displayFolder: Balance Sheet\Ratios
		lineageTag: 78c303b3-c59c-42b8-8fc5-70fdbea3ceb7

	/// Current Ratio healthy minimum threshold
	measure BS_CurrentRatio_Target = 1.5
		formatString: 0.00
		displayFolder: Balance Sheet\Targets
		lineageTag: 2c12b444-4cbd-4876-a742-1032ce32b01c

	/// Debt Ratio conservative maximum
	measure BS_DebtRatio_Target = 0.5
		formatString: 0.00
		displayFolder: Balance Sheet\Targets
		lineageTag: d82c4536-de52-4da8-9350-53c7dfed1d8b

	/// Equity Ratio minimum threshold
	measure BS_EquityRatio_Target = 0.5
		formatString: 0.00
		displayFolder: Balance Sheet\Targets
		lineageTag: e54fcaf3-a394-4b40-a2f9-b3dfbd85ebf1

	/// D/E Ratio maximum comfortable threshold
	measure BS_DebtToEquity_Target = 1.0
		formatString: 0.00
		displayFolder: Balance Sheet\Targets
		lineageTag: a34331d0-6512-4318-aec0-19ae478a7c5a

	/// Quick Ratio minimum threshold
	measure BS_QuickRatio_Target = 1.0
		formatString: 0.00
		displayFolder: Balance Sheet\Targets
		lineageTag: 2db8f3a6-3dca-43a0-a55a-657e36a4e9a9

	/// BS value for selected year - responds to Year slicer
	measure BS_Selected =
			VAR SelYear      = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR YearEnd      = DATE(SelYear, 12, 31)
			VAR rowLevel     = SELECTEDVALUE(BS_Structure[RowLevel],    "")
			VAR acctName     = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR GL_Val        = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map        = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val        = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader"} || acctName = "", BLANK(),
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: dde4a652-064b-4969-af27-3b5779e9fa8f

	/// BS value prior year - responds to Year slicer
	measure BS_PriorYear =
			VAR SelYear      = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR PrevYear     = SelYear - 1
			VAR YearEnd      = DATE(PrevYear, 12, 31)
			VAR rowLevel     = SELECTEDVALUE(BS_Structure[RowLevel],    "")
			VAR acctName     = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = PrevYear)
			VAR GL_Val        = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= PrevYear))
			VAR OB_Map        = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val        = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader"} || acctName = "", BLANK(),
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: d31485fb-562b-44a2-b088-bd8f01ba7d54

	/// YoY variance absolute
	measure BS_YoY_Var =
			VAR curr = [BS_Selected]
			VAR prev = [BS_PriorYear]
			RETURN IF(NOT ISBLANK(curr) && NOT ISBLANK(prev), curr - prev, BLANK())
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: 76fc707b-c5d6-498e-a1f3-889dad33a844

	/// YoY variance %
	measure BS_YoY_Var_Pct = DIVIDE([BS_YoY_Var], ABS([BS_PriorYear]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: c852245c-31d8-4d10-abf0-6acd48deb4e6

	/// Font color - blue theme (2026-07-07): detail rows soft grey-white #D9D9D9, group headers light blue #9DC3E6, bands/totals pure white.
	measure BS_FontColor =
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel = "Spacer",      "#000000",
			    rowLevel = "Detail",      "#D9D9D9",
			    rowLevel = "GroupHeader", "#9DC3E6",
			    "#FFFFFF"
			)
		displayFolder: Balance Sheet\Formatting
		lineageTag: a90de82a-a63a-49d3-92fc-c5bf466ac26b
		dataCategory: WebURL

	/// Background color - blue theme (2026-07-07): section bands deep blue #0F4C81 (was red #C00000), detail rows near-black blue tint #141C24 (was grey #6E6E6E) for a quieter CFO look on the black canvas.
	measure BS_BackgroundColor =
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel = "Header",      "#0F4C81",
			    rowLevel = "GroupHeader", "#1A2733",
			    rowLevel = "Detail",      "#141C24",
			    rowLevel = "Subtotal",    "#1E3448",
			    rowLevel = "Total",       "#0F4C81",
			    rowLevel = "GrandTotal",  "#0F4C81",
			    rowLevel = "Spacer",      "#000000",
			    "#141C24"
			)
		displayFolder: Balance Sheet\Formatting
		lineageTag: cb361d26-0745-4885-96dd-8987d5357750
		dataCategory: WebURL

	/// BS 2023 - headers return 0 to prevent row suppression, formatted as blank. FIXED: Accounts Receivable and Inventory now use the OB-anchored CF_AsOf_* measures instead of the stale cumulative-since-inception GL_Val fallback.
	measure BS_2023 =
			VAR SelYear = 2023
			VAR YearEnd = DATE(SelYear, 12, 31)
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			VAR acctName = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR AR_Val        = ABS(CALCULATE([CF_AsOf_AccountsReceivable], ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR Inv_Val       = ABS(CALCULATE([CF_AsOf_Inventory],          ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR GL_Val = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader", "Spacer"}, 0,
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    acctName = "Accounts Receivable",         AR_Val,
			    acctName = "Inventory",                   Inv_Val,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: #,0;-#,0;""
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: e9ce345a-29ce-46a9-ab84-0f89d51e7426

	/// BS 2024 - FIXED: same AR/Inventory fix as BS_2023.
	measure BS_2024 =
			VAR SelYear = 2024
			VAR YearEnd = DATE(SelYear, 12, 31)
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			VAR acctName = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR AR_Val        = ABS(CALCULATE([CF_AsOf_AccountsReceivable], ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR Inv_Val       = ABS(CALCULATE([CF_AsOf_Inventory],          ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR GL_Val = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader", "Spacer"}, 0,
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    acctName = "Accounts Receivable",         AR_Val,
			    acctName = "Inventory",                   Inv_Val,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: #,0;-#,0;""
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: b4a73e9b-f239-4656-9709-9bcdf98906ab

	/// BS 2025 - FIXED: same AR/Inventory fix.
	measure BS_2025 =
			VAR SelYear = 2025
			VAR YearEnd = DATE(SelYear, 12, 31)
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			VAR acctName = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR AR_Val        = ABS(CALCULATE([CF_AsOf_AccountsReceivable], ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR Inv_Val       = ABS(CALCULATE([CF_AsOf_Inventory],          ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR GL_Val = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader", "Spacer"}, 0,
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    acctName = "Accounts Receivable",         AR_Val,
			    acctName = "Inventory",                   Inv_Val,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: #,0;-#,0;""
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: 24554629-3947-44d2-9b0e-e217b1d5f2b7

	/// BS 2026 - FIXED: same AR/Inventory fix.
	measure BS_2026 =
			VAR SelYear = 2026
			VAR YearEnd = DATE(SelYear, 12, 31)
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			VAR acctName = SELECTEDVALUE(BS_Structure[AccountName], "")
			VAR TotalAssets   = CALCULATE([BS_TotalAssets],         ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrAssets    = CALCULATE([BS_CurrentAssets],       ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR NonCurrAssets = CALCULATE([BS_NonCurrentAssets],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalLiab     = CALCULATE([BS_TotalLiabilities],    ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR CurrLiab      = CALCULATE([BS_CurrentLiabilities],  ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR LTLiab        = CALCULATE([BS_LongTermLiabilities], ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR TotalEquity   = CALCULATE([BS_Equity],              ALL(Dim_Date), Dim_Date[Year] = SelYear)
			VAR AR_Val        = ABS(CALCULATE([CF_AsOf_AccountsReceivable], ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR Inv_Val       = ABS(CALCULATE([CF_AsOf_Inventory],          ALL(Dim_Date), Dim_Date[Year] = SelYear))
			VAR GL_Val = ABS(CALCULATE(SUM(GL_Actual[Amount]), TREATAS({acctName}, Dim_Accounts[AccountName]), ALL(Dim_Date), Dim_Date[Year] <= SelYear))
			VAR OB_Map = SWITCH(acctName, "Cash", 110100, "Prepaid Expenses", 130100, "Machinery & Equipment", 140100, "Buildings", 140200, "Accum. Depreciation", 140300, "Bank Loans", 230100, "Lease Liabilities", 230200, "Share Capital", 310100, "Retained Earnings", 320100, "Current Year Result", 330100, -1)
			VAR OB_Val = ABS(SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = YearEnd && Opening_Balances[OB_Account] = OB_Map), Opening_Balances[OB_Amount]))
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel IN {"Header", "GroupHeader", "Spacer"}, 0,
			    acctName = "TOTAL ASSETS",               TotalAssets,
			    acctName = "Total Current Assets",        CurrAssets,
			    acctName = "Total Non-current Assets",    NonCurrAssets,
			    acctName = "TOTAL EQUITY",                TotalEquity,
			    acctName = "TOTAL LIABILITIES",           TotalLiab,
			    acctName = "Total Current Liabilities",   CurrLiab,
			    acctName = "Total Long-term Liabilities", LTLiab,
			    acctName = "TOTAL LIABILITIES + EQUITY",  TotalLiab + TotalEquity,
			    acctName = "Accounts Receivable",         AR_Val,
			    acctName = "Inventory",                   Inv_Val,
			    OB_Map <> -1,                             OB_Val,
			    GL_Val <> 0,                              GL_Val,
			    BLANK()
			)
		formatString: #,0;-#,0;""
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: 554e0826-1ce9-48de-a00d-670d1286f606

	/// YoY Change % - 2026 vs 2025, red/green via BS_FontColor
	measure BS_YoY_Change =
			VAR curr = [BS_2026]
			VAR prev = [BS_2025]
			VAR chg  = DIVIDE(curr - prev, ABS(prev), BLANK())
			RETURN IF(NOT ISBLANK(curr) && NOT ISBLANK(prev), chg, BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Balance Sheet\Statement Columns
		lineageTag: 0cfe0fdd-050d-4d81-a01c-410011138749

	/// YoY font color - variance semantics kept (green positive / red negative, brightened for dark background); header/group rows match their band color so no stray text shows. Blue theme 2026-07-07.
	measure BS_YoY_FontColor =
			VAR rowLevel = SELECTEDVALUE(BS_Structure[RowLevel], "")
			VAR chg      = [BS_YoY_Change]
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel = "Header",      "#0F4C81",
			    rowLevel = "GroupHeader", "#1A2733",
			    rowLevel = "Spacer",      "#000000",
			    ISBLANK(chg),  "#141C24",
			    chg > 0,       "#6BCB77",
			    chg < 0,       "#FF6B6B",
			    "#FFFFFF"
			)
		displayFolder: Balance Sheet\Formatting
		lineageTag: 6fdeaaef-a67a-46e1-8d21-56538f154fe5

	/// EBIT Margin %
	measure IS_EBITMargin = DIVIDE([EBIT], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: 8aa31bf5-a798-43a8-b93d-b106bee51055

	/// EBT = EBIT + Financial Result
	measure IS_EBT = [EBIT] + CALCULATE([Actual], Dim_Accounts[FSGroup] = "Financial Result")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 2cc43e12-448a-48e5-bcb9-57d09f01b3ff

	/// EBT Margin %
	measure IS_EBTMargin = DIVIDE([IS_EBT], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: b4d2a615-226a-46b8-ba6a-0a3a4e612022

	/// COGS total
	measure IS_COGS = CALCULATE([Actual], Dim_Accounts[FSGroup] = "COGS")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 0054adf5-f852-4f11-8b65-50881cc4a31e

	/// OPEX total
	measure IS_OPEX = CALCULATE([Actual], Dim_Accounts[FSGroup] = "Operating Expenses")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 14b8c123-3094-48eb-b057-88f43e8c3000

	/// D&A total
	measure IS_DA = CALCULATE([Actual], Dim_Accounts[FSGroup] = "D&A")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 3efd3c50-bbb7-4fee-a6e1-893e9e342670

	/// Financial Result total
	measure IS_FinancialResult = CALCULATE([Actual], Dim_Accounts[FSGroup] = "Financial Result")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: d5763e66-2289-46d5-b2ea-34b7bd7e702e

	/// Taxes total
	measure IS_Taxes = CALCULATE([Actual], Dim_Accounts[FSGroup] = "Taxes")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 539acae5-4af2-4184-8f07-452110a1e693

	/// Budget for Revenue only
	measure IS_RevenueBudget = CALCULATE([Budget], Dim_Accounts[FSGroup] = "Revenue")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 237a8f64-2f11-4001-80c4-5708f62ac55a

	/// Revenue variance vs budget absolute
	measure IS_RevenueVAR = [Revenue] - [IS_RevenueBudget]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 05aec4c5-12a6-483c-b955-7b346bcc24f7

	/// Revenue variance vs budget %
	measure IS_RevenueVAR_Pct = DIVIDE([IS_RevenueVAR], ABS([IS_RevenueBudget]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Income Statement
		lineageTag: ac2b9dac-081f-4c59-bfe2-b3da9b54d3a2

	/// Gross Margin % explicit
	measure IS_GrossMargin_Pct = DIVIDE([Gross Profit], [Revenue], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\Margins
		lineageTag: 13b68eac-211f-434e-9eaf-a306a9d57cd6

	/// IS Budget value — mirrors FS Report Value but from Budget
	measure IS_FSBudget =
			VAR CurrentFS  = SELECTEDVALUE(INCOME_Structure[FSGroup])
			VAR CurrentSub = SELECTEDVALUE(INCOME_Structure[FSSubgroup])
			VAR BudRev    = CALCULATE([Budget], Dim_Accounts[FSGroup] = "Revenue")
			VAR BudCOGS   = CALCULATE([Budget], Dim_Accounts[FSGroup] = "COGS")
			VAR BudOPEX   = CALCULATE([Budget], Dim_Accounts[FSGroup] = "Operating Expenses")
			VAR BudDA     = CALCULATE([Budget], Dim_Accounts[FSGroup] = "D&A")
			VAR BudFin    = CALCULATE([Budget], Dim_Accounts[FSGroup] = "Financial Result")
			VAR BudTaxes  = CALCULATE([Budget], Dim_Accounts[FSGroup] = "Taxes")
			VAR BudGP     = BudRev - BudCOGS
			VAR BudEBITDA = BudGP - BudOPEX
			VAR BudEBIT   = BudEBITDA - BudDA
			VAR BudNI     = BudEBIT + BudFin - BudTaxes
			RETURN
			SWITCH(
			    TRUE(),
			    CurrentFS = "Gross Profit", BudGP,
			    CurrentFS = "EBITDA",       BudEBITDA,
			    CurrentFS = "EBIT",         BudEBIT,
			    CurrentFS = "Net Income",   BudNI,
			    CALCULATE([Budget], TREATAS({CurrentFS}, Dim_Accounts[FSGroup]), TREATAS({CurrentSub}, Dim_Accounts[FSSubgroup]))
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 967e771b-17ee-459a-8cc7-e27f6c648282

	/// IS Variance = Actual - Budget (FS context-aware)
	measure IS_FSVariance = [FS Report Value] - [IS_FSBudget]
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 4a9b09ef-2b5b-4bb3-90b2-7f613bd0a581

	/// IS Variance % = Variance / ABS(Budget)
	measure IS_FSVariance_Pct = DIVIDE([IS_FSVariance], ABS([IS_FSBudget]), BLANK())
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Income Statement
		lineageTag: 42dc3615-c973-4359-bc7a-7d3bb1a8b43f

	/// Background color for IS matrix rows
	measure IS_BgColor =
			VAR fsGroup = SELECTEDVALUE(INCOME_Structure[FSGroup], "")
			RETURN
			SWITCH(
			    TRUE(),
			    fsGroup = "Net Income",                                                           "#C00000",
			    fsGroup IN {"Gross Profit", "EBITDA", "EBIT"},                                    "#6B0000",
			    fsGroup IN {"Revenue", "COGS", "Operating Expenses", "D&A", "Financial Result", "Taxes"} && ISBLANK(SELECTEDVALUE(INCOME_Structure[FSSubgroup])), "#C00000",
			    "#1A1A1A"
			)
		displayFolder: Income Statement\Formatting
		lineageTag: ed897ebe-a877-4c98-bbba-ec98d9ed5e3a

	/// Var% font color — green positive, red negative
	measure IS_VarColor =
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel], "")
			VAR v = [IS_Var_Pct]
			RETURN
			IF(
			    rowLevel = "Margin" || ISBLANK(v), "#FFFFFF",
			    IF(v >= 0, "#4CAF50", "#FF4444")
			)
		displayFolder: Income Statement\Formatting
		lineageTag: 83578dd7-0017-4eb0-88fd-c58559917dca

	/// OPEX value for donut chart - filtered by FSSubgroup context
	measure IS_OPEX_Donut =
			CALCULATE(
			    [Actual],
			    Dim_Accounts[FSGroup] = "Operating Expenses",
			    TREATAS(
			        VALUES(INCOME_Structure[FSSubgroup]),
			        Dim_Accounts[FSSubgroup]
			    )
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: eeaab0fe-2ade-4a7d-a457-a0caa3baccdd

	/// IS Jan Actual
	measure IS_Jan =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=1)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: fb7105ce-a0ea-4168-ab77-7f9e93e72982

	/// IS Feb Actual
	measure IS_Feb =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=2)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: 106c599d-eae8-4ff3-a2d3-98b777ea33b9

	/// IS Mar Actual
	measure IS_Mar =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=3)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: b2038ebf-b644-40b7-b7f6-957ac02f86d3

	/// IS Apr Actual
	measure IS_Apr =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=4)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: 3cac6c16-7c2e-44b5-8583-09d363fea78b

	/// IS May Actual
	measure IS_May =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=5)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: c6cde9c1-4a0e-43c8-9881-82d2fa90326f

	/// IS Jun Actual
	measure IS_Jun =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=6)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: aa5effbf-1832-4ed5-95ea-5cfb5587e121

	/// IS Jul Actual
	measure IS_Jul =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=7)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: d34e80a1-247a-4b6f-9336-6f54cc96cd44

	/// IS Aug Actual
	measure IS_Aug =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=8)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: fa48ea97-c001-43e8-b5d7-b36b397e27c4

	/// IS Sep Actual
	measure IS_Sep =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=9)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: 5e94275b-5935-40e6-816c-4e293cb7c7c9

	/// IS Oct Actual
	measure IS_Oct =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=10)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: 35ca5b3a-7cb2-4c4f-a997-362a9175ced8

	/// IS Nov Actual
	measure IS_Nov =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=11)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: 98987f21-3ba8-47c0-b131-58b8278f8163

	/// IS Dec Actual
	measure IS_Dec =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr, Dim_Date[Month Number]=12)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: af887881-2698-4e07-b7a1-62b595811e66

	/// IS Full Year Total
	measure IS_FY =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			VAR fsGroup  = SELECTEDVALUE(INCOME_Structure[FSGroup],  "")
			VAR fsSub    = SELECTEDVALUE(INCOME_Structure[FSSubgroup],"")
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel],  "")
			VAR vRev    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue",            ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vCOGS   = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS",               ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vOPEX   = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses", ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vDA     = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A",                ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vFin    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result",   ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vTax    = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes",              ALL(Dim_Date), Dim_Date[Year]=yr)
			VAR vGP=vRev-vCOGS  VAR vEB=vGP-vOPEX  VAR vET=vEB-vDA  VAR vBT=vET+vFin  VAR vNI=vBT-vTax
			VAR vSub=CALCULATE([Actual], Dim_Accounts[FSGroup]=fsGroup, Dim_Accounts[FSSubgroup]=fsSub, ALL(Dim_Date), Dim_Date[Year]=yr)
			RETURN SWITCH(TRUE(), rowLevel IN {"Header","Margin"}, 0, fsGroup="Revenue" && rowLevel="Detail", vRev, fsGroup="Net Revenue", vRev, fsGroup="COGS" && rowLevel="Detail", vCOGS, fsGroup="Gross Profit", vGP, fsGroup="Operating Expenses" && rowLevel="Detail", vSub, fsGroup="OPEX Total", vOPEX, fsGroup="EBITDA", vEB, fsGroup="D&A" && rowLevel="Detail", vDA, fsGroup="EBIT", vET, fsGroup="Financial Result" && rowLevel="Detail", vSub, fsGroup="EBT", vBT, fsGroup="Taxes" && rowLevel="Detail", vTax, fsGroup="Net Income", vNI, BLANK())
		formatString: #,0;-#,0;""
		displayFolder: Income Statement\Monthly
		lineageTag: f5108d36-d707-453f-afc4-133c00f61d96

	/// Revenue Actual
	measure PL_Rev_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="Revenue")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: e4e57c70-b7a0-4756-b713-c88e7a8de056

	/// Revenue Budget
	measure PL_Rev_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="Revenue")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: c40ccfed-b992-4688-9ce1-9153e7254e15

	/// Revenue Variance
	measure PL_Rev_Var = [PL_Rev_A] - [PL_Rev_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 946d8599-747c-4fd1-a3f9-0e201dde7220

	/// Revenue Variance %
	measure PL_Rev_VarPct = DIVIDE([PL_Rev_Var], ABS([PL_Rev_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: c64bbcf4-61e9-4ab9-89fa-576b29d06c77

	/// COGS Actual
	measure PL_COGS_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="COGS")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: ef5ebd8c-83f4-4462-995d-898984883c53

	/// COGS Budget
	measure PL_COGS_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="COGS")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: e0d6b136-273e-413a-b508-203d41d4b317

	/// COGS Variance
	measure PL_COGS_Var = [PL_COGS_A] - [PL_COGS_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: b878f154-f383-4098-8886-4ccff66ec2f5

	/// COGS Variance %
	measure PL_COGS_VarPct = DIVIDE([PL_COGS_Var], ABS([PL_COGS_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: 59fb8b33-e13a-43ff-9e16-5eb39619c30f

	/// Gross Profit Actual
	measure PL_GP_A = [PL_Rev_A] - [PL_COGS_A]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 3c393c66-d41a-49f5-b715-29d1dd5a8629

	/// Gross Profit Budget
	measure PL_GP_B = [PL_Rev_B] - [PL_COGS_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 1319ac92-6421-4fe4-8694-5fd42d8c569f

	/// Gross Profit Variance
	measure PL_GP_Var = [PL_GP_A] - [PL_GP_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 12837882-9f9b-4734-b596-fca1b0a57761

	/// Gross Profit Variance %
	measure PL_GP_VarPct = DIVIDE([PL_GP_Var], ABS([PL_GP_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: 817df015-e9aa-42b2-903a-3c4ca1e4cfe3

	/// Gross Margin % Actual
	measure PL_GM_Pct = DIVIDE([PL_GP_A], [PL_Rev_A], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\P&L
		lineageTag: c990eab2-bdf7-4b67-a895-d7427737c832

	/// OPEX Actual
	measure PL_OPEX_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="Operating Expenses")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: ef946ca6-6c2e-4670-8308-1f83c163c7b5

	/// OPEX Budget
	measure PL_OPEX_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="Operating Expenses")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: f7bf1118-185e-4482-b6bc-5ec0ae43ad87

	/// OPEX Variance
	measure PL_OPEX_Var = [PL_OPEX_A] - [PL_OPEX_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 22aab0d6-ac7c-40fd-a207-31b643456a5e

	/// OPEX Variance %
	measure PL_OPEX_VarPct = DIVIDE([PL_OPEX_Var], ABS([PL_OPEX_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: a86ba428-e992-4132-b4f2-e7cb306eeb01

	/// EBITDA Actual
	measure PL_EBITDA_A = [PL_GP_A] - [PL_OPEX_A]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 49d9b8d1-a4f8-4a8d-9a5d-0a966e6c289f

	/// EBITDA Budget
	measure PL_EBITDA_B = [PL_GP_B] - [PL_OPEX_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: a457d615-0582-4e9f-87c0-19a273f4ee5d

	/// EBITDA Variance
	measure PL_EBITDA_Var = [PL_EBITDA_A] - [PL_EBITDA_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 5c7945e3-2f15-44f9-ac88-417fae636d57

	/// EBITDA Variance %
	measure PL_EBITDA_VarPct = DIVIDE([PL_EBITDA_Var], ABS([PL_EBITDA_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: 3076f643-ae05-47ee-8c18-8e59c9cbfc81

	/// EBITDA Margin %
	measure PL_EBITDA_Pct = DIVIDE([PL_EBITDA_A], [PL_Rev_A], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\P&L
		lineageTag: 8d4c2e64-bb13-42d2-bcd2-3db0e8c1a9a4

	/// D&A Actual
	measure PL_DA_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="D&A")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 5c695e69-9b71-498e-b7e7-bc94f32926be

	/// D&A Budget
	measure PL_DA_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="D&A")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 36096085-b423-4d76-ace1-f1bff7b31123

	/// EBIT Actual
	measure PL_EBIT_A = [PL_EBITDA_A] - [PL_DA_A]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 0bfae7cd-6823-493b-8f54-d64e5fd09e94

	/// EBIT Budget
	measure PL_EBIT_B = [PL_EBITDA_B] - [PL_DA_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: a6d82172-f478-457d-9902-6968f61b9f9b

	/// EBIT Variance
	measure PL_EBIT_Var = [PL_EBIT_A] - [PL_EBIT_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 21f33ec6-21ae-4992-b2b0-f5794fdf4d75

	/// EBIT Variance %
	measure PL_EBIT_VarPct = DIVIDE([PL_EBIT_Var], ABS([PL_EBIT_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: 98e3da92-bbdd-403d-882c-175fe400ab51

	/// EBIT Margin %
	measure PL_EBIT_Pct = DIVIDE([PL_EBIT_A], [PL_Rev_A], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\P&L
		lineageTag: cd5e21c9-9bce-430c-b3ff-e9ef0ce230a4

	/// Financial Result Actual
	measure PL_Fin_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="Financial Result")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: c7f699f3-0a12-43ed-ac6c-b2e9d7fda5f6

	/// Financial Result Budget
	measure PL_Fin_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="Financial Result")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: b563af5b-d5c8-4326-aaa3-c0e358349b8d

	/// EBT Actual
	measure PL_EBT_A = [PL_EBIT_A] + [PL_Fin_A]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 08a67b8e-02e3-42ee-8830-f9d84591ae66

	/// EBT Budget
	measure PL_EBT_B = [PL_EBIT_B] + [PL_Fin_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: c4653ea2-8bfd-4687-817c-6a285041c5d6

	/// EBT Margin %
	measure PL_EBT_Pct = DIVIDE([PL_EBT_A], [PL_Rev_A], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\P&L
		lineageTag: 87d248ac-12c3-4bde-9d74-1444ca8be983

	/// Taxes Actual
	measure PL_Tax_A = CALCULATE([Actual], Dim_Accounts[FSGroup]="Taxes")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 8728f4e9-42e3-4261-833b-ab8f6229860b

	/// Taxes Budget
	measure PL_Tax_B = CALCULATE([Budget], Dim_Accounts[FSGroup]="Taxes")
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 033a9d6e-4ce9-430c-b28c-261d544c780d

	/// Net Income Actual
	measure PL_NI_A = [PL_EBT_A] - [PL_Tax_A]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: adeee228-c9aa-4470-917b-def0b29a1a93

	/// Net Income Budget
	measure PL_NI_B = [PL_EBT_B] - [PL_Tax_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: f3d4611d-ce84-4648-b96e-f6ecd72b5191

	/// Net Income Variance
	measure PL_NI_Var = [PL_NI_A] - [PL_NI_B]
		formatString: #,0;-#,0;-
		displayFolder: Income Statement\P&L
		lineageTag: 937c7870-5180-434a-b086-ae56fdb081dd

	/// Net Income Variance %
	measure PL_NI_VarPct = DIVIDE([PL_NI_Var], ABS([PL_NI_B]), BLANK())
		formatString: +0.0%;-0.0%;-
		displayFolder: Income Statement\P&L
		lineageTag: 3a45e086-9f2c-46b1-a5ee-e33634950392

	/// Net Income Margin %
	measure PL_NI_Pct = DIVIDE([PL_NI_A], [PL_Rev_A], BLANK())
		formatString: 0.0%
		displayFolder: Income Statement\P&L
		lineageTag: dfa698a7-f707-4fc1-b459-f778afb96879

	/// Jan Actual - Header=0, format hides as empty
	measure 'Jan Actual' = [Base_Jan_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 6465ac17-bac5-49c5-91e9-710a3d44e172

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jan Budget - Header=0, format hides as empty
	measure 'Jan Budget' = [Base_Jan_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 51654729-ab71-4899-bba5-276ee70694e1

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jan Variance - empty format for zero
	measure 'Jan Var' = [Base_Jan_A]-[Base_Jan_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: a91824eb-9b6a-4e6c-8f38-7cc5bf94b56b

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jan Variance % - empty format for zero
	measure 'Jan Var%' = DIVIDE([Base_Jan_A]-[Base_Jan_B], ABS([Base_Jan_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: e3f2ef30-ceef-43d8-a3a6-ada03ac41285

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Feb Actual - Header=0, format hides as empty
	measure 'Feb Actual' = [Base_Feb_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: c195b59a-fedb-4983-8531-44793fc6391a

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Feb Budget - Header=0, format hides as empty
	measure 'Feb Budget' = [Base_Feb_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 7446275d-b80b-44b4-8e32-5fa5d2d16c8b

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Feb Variance - empty format for zero
	measure 'Feb Var' = [Base_Feb_A]-[Base_Feb_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 3f48be34-86f9-4e43-9c38-3cdfdbccf7b6

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Feb Variance % - empty format for zero
	measure 'Feb Var%' = DIVIDE([Base_Feb_A]-[Base_Feb_B], ABS([Base_Feb_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 4c2fa032-2891-4187-ad8f-a34a6e699772

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Mar Actual - Header=0, format hides as empty
	measure 'Mar Actual' = [Base_Mar_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 8760783f-03e1-4537-b76f-1e0cff30667a

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Mar Budget - Header=0, format hides as empty
	measure 'Mar Budget' = [Base_Mar_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: a103d9a7-881a-4b4e-91c6-90ee5f0446b3

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Mar Variance - empty format for zero
	measure 'Mar Var' = [Base_Mar_A]-[Base_Mar_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 7dc5094c-f53d-422d-834d-7c8595d1ae38

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Mar Variance % - empty format for zero
	measure 'Mar Var%' = DIVIDE([Base_Mar_A]-[Base_Mar_B], ABS([Base_Mar_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 906a3fb5-0cf5-4e68-92e1-7a63b6e20dda

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Apr Actual - Header=0, format hides as empty
	measure 'Apr Actual' = [Base_Apr_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 3b9e8238-ff00-40c9-a04c-2b831e0abaaa

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Apr Budget - Header=0, format hides as empty
	measure 'Apr Budget' = [Base_Apr_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 6914b062-e23c-43d0-b871-1d9f7c2dd7db

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Apr Variance - empty format for zero
	measure 'Apr Var' = [Base_Apr_A]-[Base_Apr_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: bbbb2dd8-7cae-46e9-ad16-f8e31ca31349

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Apr Variance % - empty format for zero
	measure 'Apr Var%' = DIVIDE([Base_Apr_A]-[Base_Apr_B], ABS([Base_Apr_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 27ed9131-109d-4a58-b0fd-8ba51cabeae6

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// May Actual - Header rows = 0 with empty format, Detail future = 0 with empty format too
	measure 'May Actual' = [Base_May_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 9be1722a-0469-45a9-b4e3-363201cdf848

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// May Budget - Header=0, format hides as empty
	measure 'May Budget' = [Base_May_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 82a2bee8-35ad-4ff7-90a0-220b8fa5ff11

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// May Variance - empty format for zero
	measure 'May Var' = [Base_May_A]-[Base_May_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: be86b02e-3ce7-4756-a0f2-3acba0054691

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// May Variance % - empty format for zero
	measure 'May Var%' = DIVIDE([Base_May_A]-[Base_May_B], ABS([Base_May_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 694753b4-a0f8-47b8-b42c-0761fcfbb2e4

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Jun Actual - Header=0, format hides as empty
	measure 'Jun Actual' = [Base_Jun_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 41c6d0f4-6833-48b9-aace-cb5bdcc461f1

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jun Budget - Header=0, format hides as empty
	measure 'Jun Budget' = [Base_Jun_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: c41467c0-322f-4717-bf47-6effe3349a04

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jun Variance - empty format for zero
	measure 'Jun Var' = [Base_Jun_A]-[Base_Jun_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 1a826ff7-a641-41ea-9978-68b0b300b833

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jun Variance % - empty format for zero
	measure 'Jun Var%' = DIVIDE([Base_Jun_A]-[Base_Jun_B], ABS([Base_Jun_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: e5041385-79a6-4501-a07e-14ca5a57d857

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Jul Actual - Header=0, format hides as empty
	measure 'Jul Actual' = [Base_Jul_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 46902d8a-279e-4694-8d9b-d6b9ab88429c

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jul Budget - Header=0, format hides as empty
	measure 'Jul Budget' = [Base_Jul_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 2096a508-5888-4b64-a27f-be2093f1747b

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jul Variance - empty format for zero
	measure 'Jul Var' = [Base_Jul_A]-[Base_Jul_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 86235cf2-10c3-4991-bd34-09a1ae6e47c0

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Jul Variance % - empty format for zero
	measure 'Jul Var%' = DIVIDE([Base_Jul_A]-[Base_Jul_B], ABS([Base_Jul_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 5e57d843-e765-4f4c-8131-c27dfc3e473c

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Aug Actual - Header=0, format hides as empty
	measure 'Aug Actual' = [Base_Aug_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 5b4b5dc1-6b60-4ef2-8604-0ca3df72d4c4

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Aug Budget - Header=0, format hides as empty
	measure 'Aug Budget' = [Base_Aug_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: d95c2c52-b132-4403-aded-d9559537561e

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Aug Variance - empty format for zero
	measure 'Aug Var' = [Base_Aug_A]-[Base_Aug_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: b78a957b-f79d-460a-8cee-60a43d6124b9

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Aug Variance % - empty format for zero
	measure 'Aug Var%' = DIVIDE([Base_Aug_A]-[Base_Aug_B], ABS([Base_Aug_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: be793753-da23-4846-b716-e39813da0ee0

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Sep Actual - Header=0
	measure 'Sep Actual' = [Base_Sep_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 712fdd8a-7a53-4b0c-8150-414381bfacbf

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Sep Budget - Header=0
	measure 'Sep Budget' = [Base_Sep_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 72a3a759-2fe5-4a2b-aa09-626e903e3088

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Sep Variance - empty format for zero
	measure 'Sep Var' = [Base_Sep_A]-[Base_Sep_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: bbd1b478-08ac-4e6e-a6c9-c96803349a3d

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Sep Variance % - empty format for zero
	measure 'Sep Var%' = DIVIDE([Base_Sep_A]-[Base_Sep_B], ABS([Base_Sep_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: f853df52-b525-4159-93e5-8b9391622524

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Oct Actual - Header=0
	measure 'Oct Actual' = [Base_Oct_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 52992c49-9c70-40eb-8109-dc65ae974d6f

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Oct Budget - Header=0
	measure 'Oct Budget' = [Base_Oct_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 9d1d6add-01fb-45ee-bbf6-48f506ae434c

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Oct Variance - empty format for zero
	measure 'Oct Var' = [Base_Oct_A]-[Base_Oct_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 8f4cfa61-9525-4db5-8551-72c73a301e64

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Oct Variance % - empty format for zero
	measure 'Oct Var%' = DIVIDE([Base_Oct_A]-[Base_Oct_B], ABS([Base_Oct_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 1a94cbe1-6475-4274-a987-03766fc699e6

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Nov Actual - Header=0
	measure 'Nov Actual' = [Base_Nov_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 2a63e7b0-b709-4043-84fb-93536e9bb0a6

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Nov Budget - Header=0
	measure 'Nov Budget' = [Base_Nov_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 67fdc863-1b9b-473a-a36d-64b28d71c321

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Nov Variance - empty format for zero
	measure 'Nov Var' = [Base_Nov_A]-[Base_Nov_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 3c3ae570-3b16-4b92-9560-e3f4993b2e39

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Nov Variance % - empty format for zero
	measure 'Nov Var%' = DIVIDE([Base_Nov_A]-[Base_Nov_B], ABS([Base_Nov_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 6151309d-7c9c-4ff1-a219-30218baefce4

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Dec Actual - Header=0
	measure 'Dec Actual' = [Base_Dec_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 7e68ff75-abc9-416b-aafc-e8487d61899b

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Dec Budget - Header=0
	measure 'Dec Budget' = [Base_Dec_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 5894cc74-a773-474e-b690-20196ddcb642

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Dec Variance - empty format for zero
	measure 'Dec Var' = [Base_Dec_A]-[Base_Dec_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 97a4e708-1c1f-41fe-b678-18a7415514b4

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Dec Variance % - empty format for zero
	measure 'Dec Var%' = DIVIDE([Base_Dec_A]-[Base_Dec_B], ABS([Base_Dec_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 874e80a6-9b45-4328-a6dc-694a0ed80640

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// FY Actual - Header=0
	measure 'FY Actual' = [Base_FY_A]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: bcb39bb3-1b28-4fc1-aa7c-fa4ef2bab991

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// FY Budget - Header=0
	measure 'FY Budget' = [Base_FY_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: ac36b1ef-d783-4798-b1ec-790289d28ee3

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Full Year Variance
	measure 'FY Var  ' = [Base_FY_A]-[Base_FY_B]
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 82a857fc-6964-468b-bd1c-c17f10585997

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "#,0;-#,0;", "#,0;-#,0;""-""")

	/// Full Year Variance %
	measure 'FY Var%' = DIVIDE([Base_FY_A]-[Base_FY_B], ABS([Base_FY_B]), 0)
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 4b5b466b-df4d-4206-ae9e-d7a982424947

		formatStringDefinition = VAR rl = SELECTEDVALUE(INCOME_Structure[RowLevel], "") RETURN IF(rl = "Header", "+0.0%;-0.0%;", "+0.0%;-0.0%;""-""")

	/// Returns 1 if the selected year has any actual data, used as visual filter to hide empty months
	measure IS_HasData =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			RETURN
			IF(
			    CALCULATE(COUNTROWS(GL_Actual), ALL(Dim_Date), Dim_Date[Year] = yr) > 0,
			    1, 0
			)
		formatString: 0
		displayFolder: Income Statement\Monthly Columns
		lineageTag: df17b82a-97a4-4c03-a724-d95985859b85

	/// Last month with actual data for selected year
	measure IS_LastMonth =
			VAR yr = SELECTEDVALUE(Dim_Date[Year], MAX(Dim_Date[Year]))
			RETURN
			CALCULATE(
			    MAX(Dim_Date[Month Number]),
			    GL_Actual,
			    ALL(Dim_Date),
			    Dim_Date[Year] = yr
			)
		formatString: 0
		displayFolder: Income Statement\Monthly Columns
		lineageTag: 5a5865be-9254-4850-8cc5-cee9ae0347eb

	/// Font color for IS table rows
	measure IS_FontColor =
			VAR rowLevel = SELECTEDVALUE(INCOME_Structure[RowLevel], "")
			RETURN
			SWITCH(
			    TRUE(),
			    rowLevel = "Header",     "#FFFFFF",
			    rowLevel = "GrandTotal", "#FFFFFF",
			    rowLevel = "Total",      "#FFFFFF",
			    rowLevel = "Subtotal",   "#FFFFFF",
			    rowLevel = "Detail",     "#FFFFFF",
			    "#FFFFFF"
			)
		displayFolder: Income Statement\Formatting
		lineageTag: 7812b9fb-5e43-4862-ac04-ce29b7093ca8

	/// MATH FIX: Revenue Deductions and Financial Income carry native-negative raw signs (contra-revenue/credit convention) that made subtotal subtraction silently behave like addition. Now converts each group to its true magnitude (ABS) before combining, so Net Revenue = Revenue - Deductions, Gross Profit = Net Revenue - COGS, EBITDA = Gross Profit - OPEX, EBIT = EBITDA - D&A, EBT = EBIT + net Financial Result, Net Income = EBT - Taxes, all via correct subtraction.
	measure Base_Jan_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 77f11658-5ba6-49fb-ba53-2583814771c1

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Jan_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=1, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 7049ea54-de7a-44a2-bd58-f0f86c919f9e

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Feb_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 3407f38b-8431-4db5-81b9-9d097525f0f1

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Feb_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=2, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: d1c35eea-4453-443d-afd9-dd259cdaee1b

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Mar_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 107e2377-36d1-41ee-abbb-ad1dfd57a624

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Mar_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=3, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 2b68a5f6-22c3-4d9c-b457-5f67c0ade499

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Apr_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 096cc788-2fef-479e-940c-7191220765a6

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Apr_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=4, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 239c7c48-cfee-441b-a2f9-1e10b4b6663e

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_May_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 61a37b0c-c0e9-40ce-a264-cb0d8c92f24a

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_May_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=5, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 8fbfb557-b4e4-44bb-9238-41fda8cfd7c6

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Jun_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: f0004d95-182d-4ee8-b7d7-c5f3f748015e

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Jun_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=6, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 54719f03-4f9a-4348-9509-e88de14561fc

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Jul_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 2505b6a2-6bf2-4349-b92c-50cc79c5c8ad

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Jul_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=7, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: c8648f7e-1d6e-4bae-a6e1-298b03d88d68

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Aug_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 2b8b225a-02f4-4522-a739-168e342378cb

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Aug_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=8, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 784e6746-3432-4808-9c23-5d63ee797a69

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Sep_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 176cfdb9-ec67-4375-8130-f03bdd1b9986

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Sep_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=9, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 802c6d73-05f7-4cc1-b3ad-eba1d55848f0

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Oct_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 70fa496a-7c46-45cf-8b81-6c34f2a0ef61

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Oct_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=10, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 269c2781-75ae-4bdd-8159-1254039c4fd2

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Nov_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: cb811869-7b85-44d3-8e65-f7886a94ced8

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Nov_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=11, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: d194d786-1969-418f-9928-bf25b5ba28b4

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Dec_A =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 398cf8be-aae1-42f2-a6de-b3ff72d15d2e

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_Dec_B =
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Month Number]=12, IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 9a796da4-ece0-477b-8a63-7a51443ea1b3

	/// MATH FIX: correct subtraction waterfall using magnitudes for Deductions and net Financial Result.
	measure Base_FY_A =
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()))
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 44696baa-8b65-4a58-9892-81b6914ef888

	/// For the current open year (dynamically = Forecast_BaseYear), FY Budget is now capped at the last actual month (e.g. Jan-Apr 2026) instead of the full 12-month budget, so it stays comparable to FY Actual which is naturally truncated by having no future postings. Prior closed years are unaffected (full 12-month budget). Adds one extra Month Number<=MonthCap filter to the existing calls - no new storage-engine queries.
	measure Base_FY_B =
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			VAR hasYearFilter=HASONEVALUE(Dim_Date[Year]) VAR yr=SELECTEDVALUE(Dim_Date[Year],0)
			VAR BaseYr=[Forecast_BaseYear]
			VAR LastMo=CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year]=BaseYr)
			VAR MonthCap=IF(hasYearFilter && yr=BaseYr, LastMo, 12)
			
			VAR GroupSums = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Date[Month Number]<=MonthCap)
			
			VAR vR=SUMX(FILTER(GroupSums,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupSums,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupSums,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupSums,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupSums,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Budget], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Date[Month Number]<=MonthCap, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Budget], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Date[Month Number]<=MonthCap, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupSums,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Budget], ALL(Dim_Date), IF(hasYearFilter, Dim_Date[Year]=yr, TRUE()), Dim_Date[Month Number]<=MonthCap, Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		formatString: 0
		isHidden
		displayFolder: Income Statement\_Base
		lineageTag: 4372f0b9-71f8-4986-9611-aa4081fa258a

	/// Minimum cash target = 3x trailing 12-month average monthly OPEX (rolling coverage buffer). Assumption: no fixed covenant provided, using 3 months OPEX as a standard liquidity buffer.
	measure CF_MinCashTarget =
			VAR MaxDate=MAX(Dim_Date[Date])
			VAR Last12M=CALCULATE([IS_OPEX], DATESINPERIOD(Dim_Date[Date], MaxDate, -12, MONTH))
			RETURN DIVIDE(Last12M,12,0)*3
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: ecafbe3f-56f4-4202-8c02-1f27ccd21583

	/// Currency figures now formatted with explicit it-IT locale so the engine renders the group-separator token as a period (e.g. 3.565.247) per Italian convention, instead of defaulting to a comma.
	measure CF_Commentary =
			VAR OpCF=[CF_OperatingCF]
			VAR InvCF=[CF_InvestingCF]
			VAR Closing=[CF_ClosingCash]
			VAR MinTarget=[CF_MinCashTarget]
			VAR BelowTarget=Closing<MinTarget
			VAR CoveragePct=DIVIDE(OpCF,ABS(InvCF),BLANK())
			VAR BaseMsg =
			    SWITCH(TRUE(),
			        ISBLANK(InvCF) || InvCF=0, "No investing activity this period.",
			        OpCF<0, "Operations used " & FORMAT(ABS(OpCF),"€#,##0","it-IT") & " of cash this period, on top of " & FORMAT(ABS(InvCF),"€#,##0","it-IT") & " invested — both operating and investing activities are consuming cash.",
			        CoveragePct>=1, "Operating cash fully covers investing spend (" & FORMAT(CoveragePct,"0%") & ") — growth is largely self-funded.",
			        TRUE(), "Operating cash covers " & FORMAT(CoveragePct,"0%") & " of investing spend."
			    )
			RETURN
			IF(BelowTarget, "Cash balance is below the minimum target. " & BaseMsg, BaseMsg)
		displayFolder: Cash Flow
		lineageTag: 1dadd805-5a2a-4ad0-b15c-9bab362a397b

	/// Font color for Cash Coverage Ratio tile - red if below 2.0x target, green if healthy
	measure CF_CoverageColor =
			VAR v=[CF_CashCoverageRatio]
			RETURN IF(ISBLANK(v),"#FFFFFF",IF(v<2,"#FF4444","#4CAF50"))
		displayFolder: Cash Flow\Formatting
		lineageTag: 2f5ab7d6-721e-4e48-83c0-1773114dc38a

	/// Font/line color for Closing Cash vs minimum target - red if below target
	measure CF_CashTargetColor =
			VAR c=[CF_ClosingCash]
			VAR t=[CF_MinCashTarget]
			RETURN IF(ISBLANK(c)||ISBLANK(t),"#FFFFFF",IF(c<t,"#FF4444","#4CAF50"))
		displayFolder: Cash Flow\Formatting
		lineageTag: d42ef37e-b5aa-42c0-b32e-3072c9eb3df4

	/// Value for the Cash Bridge waterfall - one figure per CF_Structure bridge step (Opening/Operating/Investing/Financing/Closing)
	measure CF_BridgeValue =
			VAR grp=SELECTEDVALUE(CF_Structure[CFGroup],"")
			RETURN
			SWITCH(
			    TRUE(),
			    grp="Opening Cash Balance", [CF_OpeningCash],
			    grp="TOTAL OPERATING CF", [CF_OperatingCF],
			    grp="TOTAL INVESTING CF", [CF_InvestingCF],
			    grp="TOTAL FINANCING CF", [CF_FinancingCF],
			    grp="CLOSING CASH BALANCE", [CF_ClosingCash],
			    BLANK()
			)
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Cash Flow
		lineageTag: 829878da-e910-4567-b962-4bb3df82e2f0

	/// MATH FIX: was a naive lifetime cumulative SUM(GL_Actual[Amount]) with no opening-balance anchor - returned blank because prepaid postings net to ~zero over full history. Now reuses the already-correct, OB-anchored CF_AsOf_PrepaidExpenses (same fix pattern as BS_AccountsReceivable/BS_Inventory).
	measure BS_PrepaidExpenses = ABS([CF_AsOf_PrepaidExpenses])
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Balance Sheet
		lineageTag: 61a0ef51-5018-4217-a2cb-d12e66d3ae36

	/// Accounts Receivable balance as of selected date. FIXED: anchors to most recent OB snapshot <= MaxDate.
	measure CF_AsOf_AccountsReceivable =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Account] = 120100))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Account] = 120100), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[Account] = "120100")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Cash Flow\_Base
		lineageTag: 340a07f5-ab0e-400a-9ed7-3b76d51976ff

	/// Inventory balance as of selected date. FIXED: anchors to most recent OB snapshot <= MaxDate.
	measure CF_AsOf_Inventory =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Account] = 120200))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Account] = 120200), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[Account] = "120200")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Cash Flow\_Base
		lineageTag: e4797081-78b9-472b-9821-72989172fc7f

	/// Prepaid Expenses balance as of selected date. FIXED: anchors to most recent OB snapshot <= MaxDate.
	measure CF_AsOf_PrepaidExpenses =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Account] = 130100))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Account] = 130100), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[Account] = "130100")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Cash Flow\_Base
		lineageTag: 54467c5c-c141-4855-aa5c-2f2228573ee5

	/// Other Current Liabilities (AP + Salaries Payable + Taxes Payable) balance as of the selected month-end. Cumulative from inception (no Opening_Balances anchor for this group).
	measure CF_AsOf_OtherCurrentLiabilities = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date]<=MAX(Dim_Date[Date])), Dim_Accounts[FSGroup]="Current Liabilities")
		formatString: "€" #,0
		isHidden
		displayFolder: Cash Flow\_Base
		lineageTag: 533f3784-aff6-4d3a-99d5-e21d59424770

	/// Gross Financial (Interest) Expenses only - excludes Financial Income. Used for true interest coverage ratios, where netting against interest income would overstate debt-servicing capacity.
	measure IS_FinancialExpenses = CALCULATE([Actual], Dim_Accounts[FSSubgroup] = "Financial Expenses")
		formatString: "€" #,0;-"€" #,0;"€" #,0
		displayFolder: Income Statement
		lineageTag: 693639c6-6dce-4c5b-9f93-564c00bacf17

	/// Cash & Bank Accounts balance as of selected date. Anchors to most recent OB snapshot <= MaxDate for BOTH 110100 (Cash) and 110200 (Bank Accounts).
	measure BS_AsOf_Cash =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Account] IN {110100, 110200}))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Account] IN {110100, 110200}), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[FSSubgroup] = "Cash & Equivalents")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Balance Sheet\_Base
		lineageTag: 81f21b7d-17d8-472b-9dd0-525f000e5432

	/// Non-Current Assets balance as of selected date. FIXED: anchors to most recent OB snapshot <= MaxDate.
	measure BS_AsOf_NonCurrentAssets =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Group] = "Non-current Assets"))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Group] = "Non-current Assets"), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[FSGroup] = "Non-current Assets")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Balance Sheet\_Base
		lineageTag: ae2b8f96-61fc-4a4b-ae0c-bd8697fb3b3b

	/// Long-term Liabilities balance as of selected date. FIXED: anchors to most recent OB snapshot <= MaxDate.
	measure BS_AsOf_LongTermLiabilities =
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR AnchorDate = CALCULATE(MAX(Opening_Balances[OB_Date]), FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] <= MaxDate && Opening_Balances[OB_Group] = "Long-term Liabilities"))
			VAR OB = IF(ISBLANK(AnchorDate), 0, SUMX(FILTER(ALL(Opening_Balances), Opening_Balances[OB_Date] = AnchorDate && Opening_Balances[OB_Group] = "Long-term Liabilities"), Opening_Balances[OB_Amount]))
			VAR GL_Movement = CALCULATE(SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MaxDate && (ISBLANK(AnchorDate) || Dim_Date[Date] > AnchorDate)), Dim_Accounts[FSGroup] = "Long-term Liabilities")
			RETURN OB + GL_Movement
		formatString: "€" #,0
		isHidden
		displayFolder: Balance Sheet\_Base
		lineageTag: 0ab72870-75ae-4534-abd5-593c285d66cd

	/// Cumulative CapEx spend from inception through selected date - shown as a positive gross investment figure. ABS()-wrapped: CF_InvestingCF is intentionally negative-signed (cash outflow) for the Cash Flow statement; this page needs the positive spend magnitude instead.
	measure CAPEX_Cumulative = ABS(CALCULATE([CF_InvestingCF], FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date]))))
		formatString: "€" #,0
		displayFolder: CAPEX
		lineageTag: 569134cb-6cec-4f2e-b5ac-2f05bb19615d

	/// Cumulative Depreciation & Amortisation from inception through selected date. Wraps existing IS_DA.
	measure CAPEX_CumulativeDA = CALCULATE([IS_DA], FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])))
		formatString: "€" #,0
		displayFolder: CAPEX
		lineageTag: 8184cf35-ecfc-4b6a-9ef9-dbad6ac4b856

	/// Cumulative Revenue from inception through selected date. Used as denominator for CapEx capital-intensity ratio.
	measure CAPEX_CumulativeRevenue = CALCULATE([Revenue], FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])))
		formatString: "€" #,0
		displayFolder: CAPEX
		lineageTag: e18b099d-56d5-487e-ab0f-8786a8863bd8

	/// CapEx-to-Depreciation ratio. >1x = asset base growing (investing faster than assets depreciate). <1x = asset base shrinking (harvesting/underinvesting).
	measure CAPEX_ToDepreciationRatio = DIVIDE([CAPEX_Cumulative], [CAPEX_CumulativeDA], BLANK())
		formatString: 0.00"x"
		displayFolder: CAPEX
		lineageTag: 3774f026-d4f7-4164-b05e-586ae1dba04a

	/// CapEx as % of cumulative Revenue. Capital intensity indicator.
	measure CAPEX_PctOfRevenue = DIVIDE([CAPEX_Cumulative], [CAPEX_CumulativeRevenue], BLANK())
		formatString: 0.0%
		displayFolder: CAPEX
		lineageTag: b6c19528-102c-4633-82b0-fe13c2a9c5e7

	/// Cumulative CapEx spend on Machinery & Equipment (140100) since inception. ABS()-wrapped for positive display, same convention as CAPEX_Cumulative.
	measure CAPEX_Cumulative_Machinery = ABS(CALCULATE(-1 * SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])), Dim_Accounts[Account] = "140100"))
		formatString: "€" #,0
		displayFolder: CAPEX
		lineageTag: 740ee339-f619-416a-a6b7-8e925d7406cc

	/// Cumulative CapEx spend on Buildings (140200) since inception. ABS()-wrapped for positive display, same convention as CAPEX_Cumulative.
	measure CAPEX_Cumulative_Buildings = ABS(CALCULATE(-1 * SUM(GL_Actual[Amount]), FILTER(ALL(Dim_Date), Dim_Date[Date] <= MAX(Dim_Date[Date])), Dim_Accounts[Account] = "140200"))
		formatString: "€" #,0
		displayFolder: CAPEX
		lineageTag: 0b7c4829-0cdf-4297-b52d-a8e27024f7d0

	/// FORECAST ASSUMPTION - single source of truth for the annual growth rate applied to out-year projections (2027+). Adjust this one value to update all forward-year forecasts. Confirmed with user: 5%.
	measure Forecast_GrowthRate = 0.05
		formatString: 0.0%
		displayFolder: Forecast
		lineageTag: ec96d031-c769-4562-a36e-befc6fdf4889

	/// MATH FIX: correct subtraction waterfall - each Actual-YTD/Budget-remainder slice ABS'd individually before combining (Financial Income has opposite native sign conventions between Actual and Budget, so must be normalized before summing).
	measure Base_FY_Blended =
			VAR SelYear=SELECTEDVALUE(Dim_Date[Year],0) VAR LastMonth=[IS_LastMonth]
			VAR fs=SELECTEDVALUE(INCOME_Structure[FSGroup],"") VAR sub=SELECTEDVALUE(INCOME_Structure[FSSubgroup],"") VAR rl=SELECTEDVALUE(INCOME_Structure[RowLevel],"")
			
			VAR GroupActualYTD = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Actual]), ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]<=LastMonth)
			VAR GroupBudgetRest = CALCULATETABLE(ADDCOLUMNS(VALUES(Dim_Accounts[FSGroup]), "@Amt", [Budget]), ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]>LastMonth)
			
			VAR vR=SUMX(FILTER(GroupActualYTD,[FSGroup]="Revenue"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="Revenue"),[@Amt])
			VAR vDedRaw=SUMX(FILTER(GroupActualYTD,[FSGroup]="Deductions"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="Deductions"),[@Amt])
			VAR vDed=IF(ISBLANK(vDedRaw),0,ABS(vDedRaw))
			VAR vC=SUMX(FILTER(GroupActualYTD,[FSGroup]="COGS"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="COGS"),[@Amt])
			VAR vO=SUMX(FILTER(GroupActualYTD,[FSGroup]="Operating Expenses"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="Operating Expenses"),[@Amt])
			VAR vD=SUMX(FILTER(GroupActualYTD,[FSGroup]="D&A"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="D&A"),[@Amt])
			VAR vFinIncome=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]<=LastMonth, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))+ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]>LastMonth, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Income"))
			VAR vFinExpense=ABS(CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]<=LastMonth, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))+ABS(CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]>LastMonth, Dim_Accounts[FSGroup]="Financial Result", Dim_Accounts[FSSubgroup]="Financial Expenses"))
			VAR vF=vFinIncome-vFinExpense
			VAR vT=SUMX(FILTER(GroupActualYTD,[FSGroup]="Taxes"),[@Amt])+SUMX(FILTER(GroupBudgetRest,[FSGroup]="Taxes"),[@Amt])
			
			VAR DetailAmt = CALCULATE([Actual], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]<=LastMonth, Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub) + CALCULATE([Budget], ALL(Dim_Date), Dim_Date[Year]=SelYear, Dim_Date[Month Number]>LastMonth, Dim_Accounts[FSGroup]=fs, Dim_Accounts[FSSubgroup]=sub)
			
			VAR raw = SWITCH(TRUE(),
			    rl="Header",0,
			    fs="Revenue"&&rl="Detail",vR,
			    fs="Deductions",vDed,
			    fs="Net Revenue",vR-vDed,
			    fs="COGS"&&rl="Detail",DetailAmt,
			    fs="COGS Total",vC,
			    fs="Gross Profit",vR-vDed-vC,
			    fs="Operating Expenses"&&rl="Detail",DetailAmt,
			    fs="OPEX Total",vO,
			    fs="EBITDA",vR-vDed-vC-vO,
			    fs="D&A"&&rl="Detail",vD,
			    fs="EBIT",vR-vDed-vC-vO-vD,
			    fs="Financial Result"&&rl="Detail",DetailAmt,
			    fs="EBT",vR-vDed-vC-vO-vD+vF,
			    fs="Taxes"&&rl="Detail",vT,
			    fs="Net Income",vR-vDed-vC-vO-vD+vF-vT,
			    BLANK())
			RETURN IF(fs IN {"COGS","Operating Expenses","D&A","Taxes","Financial Result"} && rl="Detail", ABS(raw), raw)
		isHidden
		displayFolder: Forecast\_Base
		lineageTag: 8998e6bd-2f72-471c-b738-b132e05a8251

	/// Dynamically detects the last year with actual GL data. Rebuilt with explicit FILTER instead of the bare-table CALCULATE modifier, which wasn't correctly overriding outer date filters.
	measure Forecast_BaseYear = CALCULATE(MAX(Dim_Date[Year]), FILTER(ALL(Dim_Date), CALCULATE(COUNTROWS(GL_Actual)) > 0))
		formatString: 0
		displayFolder: Forecast
		lineageTag: 26ec00f4-94a5-4c32-b027-6ba67a58d1c1

	/// Forward-year forecast (years after the base year) via compound growth off the base year's blended FY figure. INCOME_Structure-aware - works for any P&L line. Reuses Base_FY_Blended entirely, no duplicated P&L logic.
	measure IS_ForwardForecast =
			VAR SelYear=SELECTEDVALUE(Dim_Date[Year],0)
			VAR BaseYear=[Forecast_BaseYear]
			VAR YearsForward=SelYear-BaseYear
			VAR BaseValue=CALCULATE([Base_FY_Blended], ALL(Dim_Date), Dim_Date[Year]=BaseYear)
			VAR GrowthRate=[Forecast_GrowthRate]
			RETURN IF(YearsForward>0, BaseValue*(1+GrowthRate)^YearsForward, BLANK())
		displayFolder: Forecast
		lineageTag: ec2a1438-2176-469e-b795-c6e39dc3db71

	/// Unified forecast measure spanning the full timeline: pure FY Actual for historical years, blended YTD+Budget for the base year, compound-growth projection for years after. One measure for a matrix/chart with Year as a column/axis across 2023-2029.
	measure IS_Forecast_Unified =
			VAR SelYear=SELECTEDVALUE(Dim_Date[Year],0)
			VAR BaseYear=[Forecast_BaseYear]
			RETURN
			SWITCH(
			    TRUE(),
			    SelYear<BaseYear, [FY Actual],
			    SelYear=BaseYear, [Base_FY_Blended],
			    SelYear>BaseYear, [IS_ForwardForecast],
			    BLANK()
			)
		displayFolder: Forecast
		lineageTag: 0a264c6d-02b6-4303-b3d8-4ef40110e4c4

	/// CAGR from base year to 2029. Since growth is a flat compounding assumption, this will always equal Forecast_GrowthRate exactly - included as an explicit, labeled KPI rather than making the viewer infer it from the bars.
	measure Forecast_CAGR = [Forecast_GrowthRate]
		formatString: 0.0%
		displayFolder: Forecast
		lineageTag: 6eb1aed0-876d-45d6-abcf-2a9d70850f39

	/// EBITDA Margin % using the unified forecast (Actual for historical years, blended for base year, projected for out-years). Reuses IS_Forecast_Unified at the appropriate INCOME_Structure context - no duplicated P&L logic.
	measure Forecast_EBITDAMargin =
			VAR Revenue = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="Revenue", INCOME_Structure[RowLevel]="Detail")
			VAR EBITDA = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="EBITDA")
			RETURN DIVIDE(EBITDA, Revenue, BLANK())
		formatString: 0.0%
		displayFolder: Forecast
		lineageTag: 0d85f026-8ee5-4d44-a79b-cdd23d3e0fd0

	/// Net Income Margin % using the unified forecast. Reuses IS_Forecast_Unified.
	measure Forecast_NetMargin =
			VAR Revenue = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="Revenue", INCOME_Structure[RowLevel]="Detail")
			VAR NetIncome = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="Net Income")
			RETURN DIVIDE(NetIncome, Revenue, BLANK())
		formatString: 0.0%
		displayFolder: Forecast
		lineageTag: af131090-75a5-4d72-b49b-70cb1c299e4e

	/// Gross Margin % using the unified forecast. Reuses IS_Forecast_Unified.
	measure Forecast_GrossMargin =
			VAR Revenue = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="Revenue", INCOME_Structure[RowLevel]="Detail")
			VAR GrossProfit = CALCULATE([IS_Forecast_Unified], INCOME_Structure[FSGroup]="Gross Profit")
			RETURN DIVIDE(GrossProfit, Revenue, BLANK())
		formatString: 0.0%
		displayFolder: Forecast
		lineageTag: d3ca2168-35a7-44d4-ba6f-0d348e7f4f00

	/// Forecast 2023 - fixed year, Table column. Mirrors BS_2023's convention.
	measure 2023 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2023)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: 20c229e7-f391-48f0-be22-d846252b7a99

	/// Forecast 2024 - fixed year, Table column.
	measure 2024 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2024)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: d6766157-c332-4c5b-8329-cf9ee8e76cbf

	/// Forecast 2025 - fixed year, Table column.
	measure 2025 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2025)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: 9a3477b8-ca87-45a2-b9ca-b867689fa6f0

	/// Forecast 2026 - base year, blended YTD Actual + Budget. Fixed year, Table column.
	measure 2026 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2026)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: c7c6706e-a6e7-4938-b005-2ee46887eede

	/// Forecast 2027 - projected, +5% compound. Fixed year, Table column.
	measure 2027 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2027)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: cd103ca2-3f39-4b83-bfd5-cb19a7d42844

	/// Forecast 2028 - projected, +5% compound. Fixed year, Table column.
	measure 2028 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2028)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: 11a7fac7-7ec0-4b9f-9d4e-72b746860ad6

	/// Forecast 2029 - projected, +5% compound. Fixed year, Table column.
	measure 2029 = CALCULATE([IS_Forecast_Unified], ALL(Dim_Date), Dim_Date[Year]=2029)
		formatString: #,0;-#,0;""
		displayFolder: Forecast\Statement Columns
		lineageTag: 820bbd8b-9ddd-4bad-b389-963aa0b3bb61

	/// Revenue FY26 KPI card - FIXED to the base year, immune to the page's Year slicer. Base year resolved to a VAR first (DAX engine limitation: measure reference directly inline in a CALCULATE boolean filter isn't supported).
	measure Forecast_Revenue =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE(
			    [IS_Forecast_Unified],
			    ALL(Dim_Date),
			    Dim_Date[Year] = BaseYr,
			    INCOME_Structure[FSGroup] = "Revenue",
			    INCOME_Structure[RowLevel] = "Detail"
			)
		formatString: "€" #,0
		displayFolder: Forecast\KPI Cards
		lineageTag: 0e0c189c-ec95-4d45-980f-7097b6067a6e

	/// Gross Profit FY26 KPI card - FIXED to the base year, immune to the page's Year slicer.
	measure Forecast_GrossProfit =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE(
			    [IS_Forecast_Unified],
			    ALL(Dim_Date),
			    Dim_Date[Year] = BaseYr,
			    INCOME_Structure[FSGroup] = "Gross Profit"
			)
		formatString: "€" #,0
		displayFolder: Forecast\KPI Cards
		lineageTag: 3f40e6b7-37a8-4111-8273-4ff3cbd2c455

	/// EBITDA FY26 KPI card - FIXED to the base year, immune to the page's Year slicer.
	measure Forecast_EBITDA =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE(
			    [IS_Forecast_Unified],
			    ALL(Dim_Date),
			    Dim_Date[Year] = BaseYr,
			    INCOME_Structure[FSGroup] = "EBITDA"
			)
		formatString: "€" #,0
		displayFolder: Forecast\KPI Cards
		lineageTag: e7e8f6b7-9ea9-45cb-ae88-b7b8242f81a2

	/// EBIT FY26 KPI card - FIXED to the base year, immune to the page's Year slicer.
	measure Forecast_EBIT =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE(
			    [IS_Forecast_Unified],
			    ALL(Dim_Date),
			    Dim_Date[Year] = BaseYr,
			    INCOME_Structure[FSGroup] = "EBIT"
			)
		formatString: "€" #,0
		displayFolder: Forecast\KPI Cards
		lineageTag: 05dbf4b9-be4a-4c38-81dc-30d02d3073b4

	/// Net Income FY26 KPI card - FIXED to the base year, immune to the page's Year slicer.
	measure Forecast_NetIncome =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE(
			    [IS_Forecast_Unified],
			    ALL(Dim_Date),
			    Dim_Date[Year] = BaseYr,
			    INCOME_Structure[FSGroup] = "Net Income"
			)
		formatString: "€" #,0
		displayFolder: Forecast\KPI Cards
		lineageTag: c9e8d804-1b96-42ab-ad8b-5f99cde72829

	/// Revenue series for the multi-line trend chart. FIXED: was wrapping the now-pinned Forecast_Revenue (base-year-only), making every point on the chart identical. Now calls IS_Forecast_Unified directly, which correctly varies by the chart's own Year axis context.
	measure Forecast_Revenue_Line =
			CALCULATE(
			    [IS_Forecast_Unified],
			    INCOME_Structure[FSGroup] = "Revenue",
			    INCOME_Structure[RowLevel] = "Detail"
			)
		formatString: "€" #,0
		displayFolder: Forecast\Trend Chart
		lineageTag: fe67290b-9878-46d1-8005-4dbdd6d558bc

	/// EBITDA series for the multi-line trend chart. FIXED: same issue - was wrapping the pinned Forecast_EBITDA.
	measure Forecast_EBITDA_Line =
			CALCULATE(
			    [IS_Forecast_Unified],
			    INCOME_Structure[FSGroup] = "EBITDA"
			)
		formatString: "€" #,0
		displayFolder: Forecast\Trend Chart
		lineageTag: f52fa6aa-5a56-4e53-aa76-a53facdae157

	/// Net Income series for the multi-line trend chart. FIXED: same issue - was wrapping the pinned Forecast_NetIncome.
	measure Forecast_NetIncome_Line =
			CALCULATE(
			    [IS_Forecast_Unified],
			    INCOME_Structure[FSGroup] = "Net Income"
			)
		formatString: "€" #,0
		displayFolder: Forecast\Trend Chart
		lineageTag: 7363ef28-af06-4a89-bf6e-46dfb69ac9a3

	/// Revenue KPI card - YTD through last actual month of the base year. FIXED: IS_LastMonth needs Year pinned first before it can resolve - now computed inside its own CALCULATE with BaseYr already active.
	measure KPI_Revenue_YTD =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([Revenue], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: 6a246355-8289-485b-ba57-7b9e0f215ad7

	/// Gross Profit KPI card - YTD through last actual month. Same fix as KPI_Revenue_YTD.
	measure KPI_GrossProfit_YTD =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([Gross Profit], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: 53ddf389-09e1-4e21-90da-6ca64c8902fb

	/// EBITDA KPI card - YTD through last actual month. Same fix.
	measure KPI_EBITDA_YTD =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([EBITDA], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: abeaea24-fc2b-4718-977a-d41ed22e8ff7

	/// EBIT KPI card - YTD through last actual month. Same fix.
	measure KPI_EBIT_YTD =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([EBIT], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: d45f0b01-ac56-485a-8e93-8060b0c0868c

	/// Net Income KPI card - YTD through last actual month. Same fix.
	measure KPI_NetIncome_YTD =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([Net Income], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: 68a0ea1c-0dd8-470e-847c-6c8a2299ebf1

	/// Revenue Budget KPI card - full year budget for the base year (pacing target for YTD actual comparison). Pinned.
	measure KPI_RevenueBudget_FY =
			VAR BaseYr = [Forecast_BaseYear]
			RETURN
			CALCULATE([IS_RevenueBudget], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: 6220ca80-712c-4101-8ac4-fe4f94c30c3d

	/// Revenue for the single last actual month (not YTD). Used for month-over-month commentary.
	measure KPI_Revenue_LastMonth =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([Revenue], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] = LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: ed417b34-8e3d-483f-9871-f7866ca74313

	/// Net Income for the single last actual month (not YTD).
	measure KPI_NetIncome_LastMonth =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			RETURN
			CALCULATE([Net Income], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] = LastMo)
		formatString: "€" #,0
		displayFolder: Income Statement\KPI Cards
		lineageTag: 3212c12a-2fc8-4be4-997c-14c46f5166c8

	/// All FORMAT() calls now pass explicit it-IT locale (period thousands separator, comma decimal separator), matching the same fix applied to CF_Commentary.
	measure Nav_ExecutiveTicker =
			VAR BaseYr = [Forecast_BaseYear]
			VAR LastMo = CALCULATE([IS_LastMonth], ALL(Dim_Date), Dim_Date[Year] = BaseYr)
			VAR MonthName = CALCULATE(MAX(Dim_Date[Month]), ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] = LastMo)
			
			VAR RevYTD = [KPI_Revenue_YTD]
			VAR GPYTD = [KPI_GrossProfit_YTD]
			VAR EBITDAYTD = [KPI_EBITDA_YTD]
			VAR NIYTD = [KPI_NetIncome_YTD]
			
			VAR BudgetYTD = CALCULATE([IS_RevenueBudget], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] <= LastMo)
			VAR VarPct = DIVIDE(RevYTD - BudgetYTD, ABS(BudgetYTD), 0)
			VAR VarLabel = IF(VarPct >= 0, "ahead of", "behind")
			
			VAR RevPY = CALCULATE([Revenue], ALL(Dim_Date), Dim_Date[Year] = BaseYr - 1, Dim_Date[Month Number] <= LastMo)
			VAR RevPYPct = DIVIDE(RevYTD - RevPY, ABS(RevPY), BLANK())
			VAR PYLabel = IF(RevPYPct >= 0, "up", "down")
			
			VAR EBITDAMarginYTD = DIVIDE(EBITDAYTD, RevYTD, BLANK())
			VAR NIMarginYTD = DIVIDE(NIYTD, RevYTD, BLANK())
			
			VAR ClosingCash = CALCULATE([CF_ClosingCash], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] = LastMo)
			VAR MinTarget = CALCULATE([CF_MinCashTarget], ALL(Dim_Date), Dim_Date[Year] = BaseYr, Dim_Date[Month Number] = LastMo)
			VAR CashGap = ClosingCash - MinTarget
			VAR CashLabel = IF(CashGap >= 0, "above", "below")
			
			RETURN
			MonthName & " " & BaseYr & " YTD:   Revenue " & FORMAT(RevYTD,"€ #,##0,,.0","it-IT") & "M (" & FORMAT(ABS(RevPYPct),"0.0%","it-IT") & " " & PYLabel & " YoY, " & FORMAT(ABS(VarPct),"0.0%","it-IT") & " " & VarLabel & " budget)" &
			"     |     Gross Profit " & FORMAT(GPYTD,"€ #,##0,,.0","it-IT") & "M" &
			"     |     EBITDA " & FORMAT(EBITDAYTD,"€ #,##0,,.0","it-IT") & "M (" & FORMAT(EBITDAMarginYTD,"0.0%","it-IT") & " margin)" &
			"     |     Net Income " & FORMAT(NIYTD,"€ #,##0,,.0","it-IT") & "M (" & FORMAT(NIMarginYTD,"0.0%","it-IT") & " margin)" &
			"     |     Cash " & FORMAT(ClosingCash,"€ #,##0,,.0","it-IT") & "M, " & FORMAT(ABS(CashGap),"€ #,##0,,.0","it-IT") & "M " & CashLabel & " minimum target"
		displayFolder: Navigation
		lineageTag: 1f812c75-49de-4b06-92d3-722ff77c4a3c

	/// The true last calendar date with actual GL data ("today" for this model). Dynamic - no hardcoding. Used to truncate trend charts/tables so they stop at real data instead of drawing frozen carry-forward values into unknown future dates.
	measure Forecast_LastActualDate = CALCULATE(MAX(Dim_Date[Date]), FILTER(ALL(Dim_Date), CALCULATE(COUNTROWS(GL_Actual)) > 0))
		formatString: dd/mm/yyyy
		displayFolder: Forecast
		lineageTag: 9fffc492-0a25-48e5-bd0b-0e2ddf5a5954

	/// Dynamic 'Data as of' label for the Navigation page header. Reuses Forecast_LastActualDate - no hardcoding, self-updates as real data grows.
	measure Nav_DataAsOf = FORMAT([Forecast_LastActualDate], "MMMM YYYY")
		displayFolder: Navigation
		lineageTag: df89f83a-d4ad-41c7-872b-00dcc666edb4

	/// Month name corresponding to the last actual GL date ("today"). Fixed: VAR renamed to avoid colliding with DAX's built-in LASTDATE() function.
	measure IS_DefaultMonthName =
			VAR LatestActualDt = [Forecast_LastActualDate]
			RETURN CALCULATE(SELECTEDVALUE(Dim_Date[Month]), ALL(Dim_Date), Dim_Date[Date] = LatestActualDt)
		displayFolder: Income Statement\Selected Month
		lineageTag: 7b2c8860-f248-408b-b12c-d1ec032eca65

	/// Actual for whatever month is selected in the slicer (defaults to last actual month if none selected). Reuses the 12 existing month measures - no duplicated logic. Core of the column-count reduction fix: replaces 12 simultaneous Actual columns with 1.
	measure IS_SelMonth_Actual =
			VAR SelMonth = SELECTEDVALUE(Dim_Date[Month], [IS_DefaultMonthName])
			RETURN
			SWITCH(
			    SelMonth,
			    "Jan", [Jan Actual], "Feb", [Feb Actual], "Mar", [Mar Actual], "Apr", [Apr Actual],
			    "May", [May Actual], "Jun", [Jun Actual], "Jul", [Jul Actual], "Aug", [Aug Actual],
			    "Sep", [Sep Actual], "Oct", [Oct Actual], "Nov", [Nov Actual], "Dec", [Dec Actual],
			    BLANK()
			)
		displayFolder: Income Statement\Selected Month
		lineageTag: 6dd0b548-1706-48dd-ac05-6532aaed706b

	/// Budget for whatever month is selected. Reuses the 12 existing month measures.
	measure IS_SelMonth_Budget =
			VAR SelMonth = SELECTEDVALUE(Dim_Date[Month], [IS_DefaultMonthName])
			RETURN
			SWITCH(
			    SelMonth,
			    "Jan", [Jan Budget], "Feb", [Feb Budget], "Mar", [Mar Budget], "Apr", [Apr Budget],
			    "May", [May Budget], "Jun", [Jun Budget], "Jul", [Jul Budget], "Aug", [Aug Budget],
			    "Sep", [Sep Budget], "Oct", [Oct Budget], "Nov", [Nov Budget], "Dec", [Dec Budget],
			    BLANK()
			)
		displayFolder: Income Statement\Selected Month
		lineageTag: a14d889e-88f1-491d-932b-dc8f0c39d59e

	/// Variance for whatever month is selected. Reuses the 12 existing month measures.
	measure IS_SelMonth_Var =
			VAR SelMonth = SELECTEDVALUE(Dim_Date[Month], [IS_DefaultMonthName])
			RETURN
			SWITCH(
			    SelMonth,
			    "Jan", [Jan Var], "Feb", [Feb Var], "Mar", [Mar Var], "Apr", [Apr Var],
			    "May", [May Var], "Jun", [Jun Var], "Jul", [Jul Var], "Aug", [Aug Var],
			    "Sep", [Sep Var], "Oct", [Oct Var], "Nov", [Nov Var], "Dec", [Dec Var],
			    BLANK()
			)
		displayFolder: Income Statement\Selected Month
		lineageTag: 9af57be6-068b-417f-8838-8343db1bddb9

	/// Variance % for whatever month is selected. Reuses the 12 existing month measures.
	measure IS_SelMonth_VarPct =
			VAR SelMonth = SELECTEDVALUE(Dim_Date[Month], [IS_DefaultMonthName])
			RETURN
			SWITCH(
			    SelMonth,
			    "Jan", [Jan Var%], "Feb", [Feb Var%], "Mar", [Mar Var%], "Apr", [Apr Var%],
			    "May", [May Var%], "Jun", [Jun Var%], "Jul", [Jul Var%], "Aug", [Aug Var%],
			    "Sep", [Sep Var%], "Oct", [Oct Var%], "Nov", [Nov Var%], "Dec", [Dec Var%],
			    BLANK()
			)
		displayFolder: Income Statement\Selected Month
		lineageTag: 309b2f43-bb70-41d4-bd26-152867f953ac

	column Column
		formatString: 0
		lineageTag: cd43175d-8549-43da-8f51-6049df19fb52
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition M_Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 4cf8cb14c0844070891f84b085ba57c4

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

